; wEventFlags bit flags

	const_def
; The first eight flags are reset upon reloading the map
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_1
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_2
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_3
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_4
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_5
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_6
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_7
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_8
; marks initialized events
	const EVENT_INITIALIZED_EVENTS
; base game events
	const EVENT_BEAT_ELITE_FOUR
; TM events
	const EVENT_GOT_TM05_DARK_PULSE
	const EVENT_GOT_TM06_DAZZLE_BEAM
	const EVENT_GOT_TM17_HEADBUTT
	const EVENT_GOT_TM44_SWIFT
	const_skip
	const_skip
	const EVENT_GOT_TM23_IRON_TAIL
	const EVENT_GOT_TM16_ICY_WIND
	const EVENT_GOT_TM24_DRAGONBREATH
; HMs (EVENT_GOT_HM07_WATERFALL is with the Johto itemballs)
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_GOT_FLASHLIGHT
	const_skip
	const_skip ; unused
; Rods
	const EVENT_GOT_OLD_ROD
	const EVENT_GOT_GOOD_ROD
	const EVENT_GOT_SUPER_ROD
; Johto story events
	const EVENT_GOT_A_STARTER
	const EVENT_GOT_BURGELA_STARTER
	const EVENT_GOT_PORYGON_STARTER
	const EVENT_GOT_SPIRRIP_STARTER
	const EVENT_GOT_FOAMPOSITES
	const EVENT_GOT_BASEMENT_KEY
	const EVENT_GOT_CHAINSAW
	const READ_NORTHFOREST_GRAVE
	const EVENT_TOOK_THAT
	const EVENT_GOT_MORPHBALL
	const EVENT_GOT_ENERGY_TANK
	const EVENT_USED_THE_CITY_GEAR_EMPLOYEE_CARD_KEY
	const EVENT_GOT_LINK_CABLE_IN_UNIVERCITY
	const EVENT_BOUGHT_BELDUM
	const EVENT_SEEN_WHITTLIN_THEFT
	const EVENT_TALKED_TO_UNIVERCITY_MART_BASEMENT_CLERK
	const EVENT_GOT_SLOWPOKETAIL_FROM_MISSION
	const EVENT_IS_GAY
	const EVENT_GOT_SAVED
	const EVENT_GAVE_EEVEE_TWIN_ICE_STONE
	const EVENT_GAVE_EEVEE_TWIN_LEAF_STONE
	const EVENT_FED_EEVEE
	const EVENT_GOT_UMBREON
	const EVENT_EARNED_ODD_EGG
	const EVENT_GAVE_VAPOREON_TEA
	const EVENT_GAVE_VAPOREON_MONSTER
	const EVENT_GAVE_VAPOREON_PBR
	const EVENT_TAUGHT_JOLTEON
	const EVENT_TAUGHT_FLAREON
	const EVENT_GOT_LEAFEON_BASIL
	const EVENT_USED_CGHQ_BASEMENT_KEY
	const EVENT_RECEIVED_CARD_KEY
	const EVENT_SATISFIED_SYLVEON
	const EVENT_GOT_WEED_FROM_SAM
	const EVENT_SAW_WHINPIN_APOLOGY
	const EVENT_GOT_ARANT_NUGGET
	const EVENT_GOT_BOOZER_BIG_PEARL
	const EVENT_VOLCANO_INTERIOR_3F_LEVER
	const EVENT_VOLCANO_INTERIOR_4F_LEVER
	const EVENT_VOLCANO_LADDER_OPTIONAL
	const EVENT_VOLCANO_LADDER_1
	const EVENT_VOLCANO_LADDER_2
	const EVENT_VOLCANO_LADDER_3
	const EVENT_VOLCANO_LADDER_4
	const EVENT_FELL_INTO_BROCANO
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Overworld Pokemon
	const EVENT_NORTHERNFOREST_MORELULL1
	const EVENT_NORTHERNFOREST_MORELULL2
	const EVENT_NORTHERNFOREST_SUICUNE
	const EVENT_METROID_INTRO_ZOOMER_1
	const EVENT_METROID_INTRO_ZOOMER_2
	const EVENT_METROID_HALLWAY_ZOOMER_1
	const EVENT_METROID_END_ZOOMER_1
	const EVENT_METROID_END_ZOOMER_2
	const EVENT_METROID_END_ZOOMER_3
	const EVENT_EEVEE_RANCH_HIVES_COMBEE1
	const EVENT_EEVEE_RANCH_HIVES_COMBEE2
	const EVENT_EEVEE_RANCH_HIVES_COMBEE3
	const EVENT_EEVEE_RANCH_HIVES_COMBEE4
	const EVENT_EEVEE_RANCH_HIVES_COMBEE5
	const EVENT_EEVEE_RANCH_HIVES_COMBEE6
	const EVENT_ROUTE_G_METROID_CAVE_ZOOMER_1
	const EVENT_ROUTE_G_METROID_CAVE_ZOOMER_2
	const EVENT_FOUGHT_REGIMAGMA
	const EVENT_OVERWORLD_DRAMPA
	const EVENT_FOUGHT_M_BLOCK
	const EVENT_BEAT_OCTOROK_1
	const EVENT_BEAT_OCTOROK_2
	const EVENT_BEAT_OCTOROK_3
	const EVENT_BEAT_OCTOROK_4
	const EVENT_BEAT_OCTOROK_5
	const EVENT_BEAT_OCTOROK_6
	const EVENT_BEAT_OCTOROK_7
	const EVENT_BEAT_OCTOROK_8
	const EVENT_BEAT_CRAB_1
	const EVENT_BEAT_CRAB_2
	const EVENT_BEAT_CRAB_3
	const EVENT_BEAT_CRAB_4
	const EVENT_BEAT_CRAB_5
	const EVENT_BEAT_CRAB_6
	const EVENT_BEAT_CRAB_7
	const EVENT_BEAT_CRAB_8
	const EVENT_MISPLACED_WOODS_GEL_1
	const EVENT_MISPLACED_WOODS_GEL_2
	const EVENT_MISPLACED_WOODS_GEL_3
	const EVENT_MISPLACED_WOODS_GEL_4
	const EVENT_MISPLACED_WOODS_GEL_5
	const EVENT_MISPLACED_WOODS_GEL_6
	const EVENT_MISPLACED_CAVERN_2F_GEL_1
	const EVENT_BEAT_MISPLACED_CAVERN_1F_KEESE_1
	const EVENT_BEAT_MISPLACED_CAVERN_1F_KEESE_2
	const EVENT_BEAT_MISPLACED_CAVERN_2F_KEESE_1
; Johto hidden items
	const EVENT_NORTHERNFOREST_LEFT_HONEY
	const EVENT_NORTHERNFOREST_RIGHT_HONEY
	const EVENT_NORTHERNFOREST_HIDDEN_CARBOS
	const EVENT_NORTHERNFOREST_HIDDEN_ETHER
	const EVENT_UNIVERCITY_MART_B1F_HIDDEN_FULL_HEAL
	const EVENT_UNIVERCITY_MART_B1F_HIDDEN_HYPER_POTION
	const EVENT_UNIVERCITY_MART_B1F_HIDDEN_REVIVE
	const EVENT_UNIVERCITY_MART_B1F_HIDDEN_ETHER
	const EVENT_ROUTE_C_HIDDEN_FULL_HEAL
	const EVENT_ROUTE_D_HIDDEN_SUPER_POTION
	const EVENT_ROUTE_D_HIDDEN_FULL_HEAL
	const EVENT_EEVEE_RANCH_HIVES_HIDDEN_HONEY1
	const EVENT_EEVEE_RANCH_HIVES_HIDDEN_HONEY2
	const EVENT_EEVEE_RANCH_HIVES_HIDDEN_HONEY3
	const EVENT_EEVEE_RANCH_HIVES_HIDDEN_HONEY4
	const EVENT_EEVEE_RANCH_HIVES_HIDDEN_BASIL
	const EVENT_ROUTE_E_HIDDEN_HYPER_POTION
	const EVENT_ROUTE_E_HIDDEN_MAX_REPEL
	const EVENT_ROUTE_E_HIDDEN_FULL_RESTORE
	const EVENT_JUNGLE_HIDDEN_MAX_REVIVE
	const EVENT_JUNGLE_HIDDEN_MAX_POTION
	const EVENT_JUNGLE_HIDDEN_CARBOS
	const EVENT_VOLCANO_INTERIOR_1F_HIDDEN_ICE_HEAL
	const EVENT_VOLCANO_INTERIOR_1F_HIDDEN_RARE_CANDY
	const EVENT_VOLCANO_INTERIOR_1F_HIDDEN_ULTRA_BALL
	const EVENT_VOLCANO_INTERIOR_1F_HIDDEN_FULL_RESTORE
	const EVENT_VOLCANO_INTERIOR_2F_HIDDEN_DIRE_HIT
	const EVENT_VOLCANO_INTERIOR_2F_HIDDEN_ULTRA_BALL
	const EVENT_VOLCANO_INTERIOR_3F_HIDDEN_MAX_POTION
	const EVENT_VOLCANO_INTERIOR_3F_HIDDEN_MAX_ELIXER
	const EVENT_VOLCANO_INTERIOR_3F_HALL_HIDDEN_MAX_POTION
	const EVENT_VOLCANO_INTERIOR_4F_HIDDEN_FULL_HEAL
	const EVENT_VOLCANO_INTERIOR_4F_HIDDEN_REVIVE
	const EVENT_VOLCANO_INTERIOR_4F_HIDDEN_MAX_POTION
	const EVENT_VOLCANO_INTERIOR_5F_HIDDEN_MAX_ELIXER
	const EVENT_VOLCANO_INTERIOR_5F_HIDDEN_RARE_CANDY
	const EVENT_VOLCANO_INTERIOR_5F_HIDDEN_FULL_RESTORE
	const EVENT_VOLCANO_INTERIOR_5F_HIDDEN_GREAT_BALL
	const EVENT_VOLCANO_INTERIOR_B1F_HIDDEN_SUPER_POTION
	const EVENT_VOLCANO_INTERIOR_B1F_HIDDEN_RARE_CANDY
	const EVENT_VOLCANO_INTERIOR_B1F_HIDDEN_ETHER
	const EVENT_VOLCANO_INTERIOR_B1F_HIDDEN_NUGGET
	const EVENT_VOLCANO_INTERIOR_6F_HIDDEN_HYPER_POTION
	const EVENT_VOLCANO_INTERIOR_6F_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_42_HIDDEN_MAX_POTION
	const EVENT_ROUTE_44_HIDDEN_ELIXER
	const EVENT_ROUTE_45_HIDDEN_PP_UP
	const EVENT_VIOLET_CITY_HIDDEN_HYPER_POTION
	const EVENT_AZALEA_TOWN_HIDDEN_FULL_HEAL
	const EVENT_CIANWOOD_CITY_HIDDEN_REVIVE
	const EVENT_CIANWOOD_CITY_HIDDEN_MAX_ETHER
	const EVENT_ECRUTEAK_CITY_HIDDEN_HYPER_POTION
	const EVENT_LAKE_OF_RAGE_HIDDEN_FULL_RESTORE
	const EVENT_LAKE_OF_RAGE_HIDDEN_RARE_CANDY
	const EVENT_LAKE_OF_RAGE_HIDDEN_MAX_POTION
	const EVENT_SILVER_CAVE_OUTSIDE_HIDDEN_FULL_RESTORE
	const_skip
; Crystal-exclusive events in Johto
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Jumpes
	const EVENT_GOT_VOLCANO_JUMP
	const_skip
	const_skip
	const_skip
; Kanto story events
	const EVENT_LA_PHONE_1
	const EVENT_HAVE_NOT_STOLEN
	const EVENT_CAN_STEAL
	const EVENT_HAS_STOLEN_EVER
	const EVENT_HAS_STOLEN
	const EVENT_FOLLOWED_BY_CARD
	const EVENT_FOLLOWED_BY_ULTRA_BALL
	const EVENT_FOLLOWED_BY_HEART
	const EVENT_FOLLOWED_BY_LUCKY_EGG
	const EVENT_FOLLOWED_BY_TM
	const EVENT_BOUGHT_BRIGHT_CARD
	const EVENT_BOUGHT_PSYCHIC
	const EVENT_BOUGHT_SIGNAL_BEAM
	const EVENT_BOUGHT_OMINOUS_WIND
	const EVENT_BOUGHT_PLAY_ROUGH
	const EVENT_BEAT_SHOPKEEPER
	const EVENT_GOT_ITEM_FROM_LA_YOUNGSTER
	const EVENT_BOMBED_MISPLACED_WOODS_WALL
	const EVENT_GOT_SWORD_ON_BEACH
	const EVENT_SAW_KAEPORA_ON_BEACH
	const EVENT_SAW_KAEPORA_IN_WOODS
	const EVENT_BOMBED_AWAKENING_BEACH_2_WALL
	const EVENT_GOT_APPLIN
	const EVENT_GOT_TART_APPLE
	const EVENT_GOT_SWEET_APPLE
	const EVENT_GOT_TM29_PSYCHIC
	const EVENT_UNLOCKED_DUNGEON
; Kanto hidden items
	const EVENT_OLD_MANS_HOUSE_HIDDEN_MAX_REVIVE
	const EVENT_QUADRUPLETS_HOUSE_HIDDEN_FULL_RESTORE
	const EVENT_UNDERGROUND_PATH_HIDDEN_X_SPECIAL
	const EVENT_MISPLACED_WOODS_HIDDEN_X_ACCURACY
	const EVENT_MISPLACED_WOODS_HIDDEN_X_DEFEND
	const EVENT_MISPLACED_WOODS_HIDDEN_MAX_POTION
	const EVENT_MISPLACED_CAVERN_1F_HIDDEN_PROTEIN
	const EVENT_MISPLACED_CAVERN_1F_HIDDEN_IRON
	const EVENT_MISPLACED_CAVERN_2F_HIDDEN_MOON_STONE
	const EVENT_MISPLACED_CAVERN_2F_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_2_HIDDEN_FULL_HEAL
	const EVENT_ROUTE_2_HIDDEN_FULL_RESTORE
	const EVENT_ROUTE_2_HIDDEN_REVIVE
	const EVENT_ROUTE_4_HIDDEN_ULTRA_BALL
	const EVENT_ROUTE_9_HIDDEN_ETHER
	const EVENT_ROUTE_12_HIDDEN_ELIXER
	const EVENT_ROUTE_13_HIDDEN_CALCIUM
	const EVENT_ROUTE_11_HIDDEN_REVIVE
	const EVENT_ROUTE_17_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_17_HIDDEN_MAX_ELIXER
	const EVENT_ROUTE_25_HIDDEN_POTION
	const EVENT_FOUND_LEFTOVERS_IN_CELADON_CAFE
	const EVENT_FOUND_BERSERK_GENE_IN_CERULEAN_CITY
	const EVENT_FOUND_MACHINE_PART_IN_CERULEAN_GYM
	const EVENT_VERMILION_CITY_HIDDEN_FULL_HEAL
	const EVENT_CELADON_CITY_HIDDEN_PP_UP
	const EVENT_CINNABAR_ISLAND_HIDDEN_RARE_CANDY
	const EVENT_BURNED_TOWER_1F_HIDDEN_ULTRA_BALL
	const EVENT_GINA_GAVE_LEAF_STONE
	const EVENT_ALAN_GAVE_FIRE_STONE
	const EVENT_DANA_GAVE_THUNDERSTONE
	const EVENT_TULLY_GAVE_WATER_STONE
	const EVENT_TIFFANY_GAVE_PINK_BOW
	const EVENT_AWAKENING_BEACH_HYPER_POTION
; Maybe Village Shrine Events
	const EVENT_MAYBE_VILLAGE_SHRINE_BUTTON_PRESSED
	const EVENT_MAYBE_VILLAGE_SHRINE_BLOCK_ON_BLUE
	const EVENT_MAYBE_VILLAGE_SHRINE_DEFEATED_ENEMY
	const EVENT_MAYBE_VILLAGE_SHRINE_PUSHED_QUESTION_BLOCK
	const EVENT_MAYBE_VILLAGE_SHRINE_PRESSED_LAST_BUTTON
	const EVENT_BEAT_SHRINE_WALL_TRAP_1
	const EVENT_BEAT_SHRINE_WALL_TRAP_2
	const EVENT_BEAT_SHRINE_WALL_TRAP_3
	const EVENT_BEAT_SHRINE_WALL_TRAP_4
	const EVENT_GOT_DUNGEON_KEY
; Awakening Dungeon Events
	const EVENT_GOT_BIG_KEY
	const EVENT_AWAKENING_DUNGEON_BIG_KEY
	const EVENT_AWAKENING_DUNGEON_BOTTOM_RIGHT_BUTTON
	const EVENT_AWAKENING_DUNGEON_BOTTOM_RIGHT_SMALL_KEY
	const EVENT_AWAKENING_DUNGEON_SECOND_BOTTOM_RIGHT_KEY
	const EVENT_AWAKENING_DUNGEON_PUSHED_BOTTOM_RIGHT_BLOCK
	const EVENT_AWAKENING_DUNGEON_PRESSED_TOP_MIDDLE_BUTTON
	const EVENT_AWAKENING_DUNGEON_OPEN_BOSS_DOOR
	const EVENT_AWAKENING_DUNGEON_UNLOCKED_MINI_BOSS_DOOR
	const EVENT_AWAKENING_DUNGEON_UNLOCKED_FRONT_KEY_BLOCK
	const EVENT_AWAKENING_DUNGEON_PRESSED_TOP_LEFT_BUTTON
	const EVENT_BEAT_DUNGEON_BLADE_TRAP_1
	const EVENT_BEAT_DUNGEON_BLADE_TRAP_2
	const EVENT_BEAT_DUNGEON_BLADE_TRAP_3
	const EVENT_BEAT_DUNGEON_BLADE_TRAP_4
	const EVENT_BEAT_DUNGEON_BLADE_TRAP_5
	const EVENT_BEAT_AWAKENING_DUNGEON_GEL_1
	const EVENT_BEAT_AWAKENING_DUNGEON_GEL_2
	const EVENT_BEAT_AWAKENING_DUNGEON_GEL_3
	const EVENT_BEAT_AWAKENING_DUNGEON_B1F_KEESE_1
	const EVENT_BEAT_AWAKENING_DUNGEON_B1F_KEESE_2
	const EVENT_BEAT_AWAKENING_DUNGEON_B1F_GEL_1
	const EVENT_BEAT_AWAKENING_DUNGEON_B1F_GEL_2
	const EVENT_AWAKENING_DUNGEON_B1F_PUSHED_BOTTOM_LEFT_BLOCK
	const EVENT_AWAKENING_DUNGEON_B1F_PUSHED_MIDDLE_LEFT_BLOCK
	const EVENT_AWAKENING_DUNGEON_PRESSED_INCORRECT_BUTTON
	const EVENT_AWAKENING_DUNGEON_PRESSED_CORRECT_BUTTON
	const EVENT_GOT_ZORA_FLIPPERS
; Unused: next 302 events
	const_next 600
; Kurt Apricorn events
	const EVENT_GAVE_KURT_RED_APRICORN
	const EVENT_GAVE_KURT_BLU_APRICORN
	const EVENT_GAVE_KURT_YLW_APRICORN
	const EVENT_GAVE_KURT_GRN_APRICORN
	const EVENT_GAVE_KURT_WHT_APRICORN
	const EVENT_GAVE_KURT_BLK_APRICORN
	const EVENT_GAVE_KURT_PNK_APRICORN
; Phone events
; Unused: next 60 events
	const_next 666
; Ruins of Alph puzzles
	const EVENT_SOLVED_HO_OH_PUZZLE
	const EVENT_SOLVED_KABUTO_PUZZLE
	const EVENT_SOLVED_OMANYTE_PUZZLE
	const EVENT_SOLVED_AERODACTYL_PUZZLE
; Decorations
	const EVENT_DECO_BED_1
	const EVENT_DECO_BED_2
	const EVENT_DECO_BED_3
	const EVENT_DECO_BED_4
	const EVENT_DECO_CARPET_1
	const EVENT_DECO_CARPET_2
	const EVENT_DECO_CARPET_3
	const EVENT_DECO_CARPET_4
	const EVENT_DECO_PLANT_1
	const EVENT_DECO_PLANT_2
	const EVENT_DECO_PLANT_3
	const EVENT_DECO_POSTER_1
	const EVENT_DECO_POSTER_2
	const EVENT_DECO_POSTER_3
	const EVENT_DECO_POSTER_4
	const EVENT_DECO_FAMICOM
	const EVENT_DECO_SNES
	const EVENT_DECO_N64
	const EVENT_DECO_VIRTUAL_BOY
	const EVENT_DECO_PIKACHU_DOLL
	const EVENT_DECO_SURFING_PIKACHU_DOLL
	const EVENT_DECO_CLEFAIRY_DOLL
	const EVENT_DECO_JIGGLYPUFF_DOLL
	const EVENT_DECO_BULBASAUR_DOLL
	const EVENT_DECO_CHARMANDER_DOLL
	const EVENT_DECO_SQUIRTLE_DOLL
	const EVENT_DECO_POLIWAG_DOLL
	const EVENT_DECO_DIGLETT_DOLL
	const EVENT_DECO_STARMIE_DOLL
	const EVENT_DECO_MAGIKARP_DOLL
	const EVENT_DECO_ODDISH_DOLL
	const EVENT_DECO_GENGAR_DOLL
	const EVENT_DECO_SHELLDER_DOLL
	const EVENT_DECO_GRIMER_DOLL
	const EVENT_DECO_VOLTORB_DOLL
	const EVENT_DECO_WEEDLE_DOLL
	const EVENT_DECO_UNOWN_DOLL
	const EVENT_DECO_GEODUDE_DOLL
	const EVENT_DECO_MACHOP_DOLL
	const EVENT_DECO_TENTACOOL_DOLL
	const EVENT_PLAYERS_ROOM_POSTER
	const EVENT_DECO_GOLD_TROPHY
	const EVENT_DECO_SILVER_TROPHY
	const EVENT_DECO_BIG_SNORLAX_DOLL
	const EVENT_DECO_BIG_ONIX_DOLL
	const EVENT_DECO_BIG_LAPRAS_DOLL
; More Johto story events
	const EVENT_WARPED_FROM_ROUTE_35_NATIONAL_PARK_GATE
	const EVENT_SWITCH_1
	const EVENT_SWITCH_2
	const EVENT_SWITCH_3
	const EVENT_EMERGENCY_SWITCH
	const EVENT_SWITCH_4
	const EVENT_SWITCH_5
	const EVENT_SWITCH_6
	const EVENT_SWITCH_7
	const EVENT_SWITCH_8
	const EVENT_SWITCH_9
	const EVENT_SWITCH_10
	const EVENT_SWITCH_11
	const EVENT_SWITCH_12
	const EVENT_SWITCH_13
	const EVENT_SWITCH_14
	const EVENT_UNCOVERED_STAIRCASE_IN_MAHOGANY_MART
	const EVENT_TURNED_OFF_SECURITY_CAMERAS
	const EVENT_SECURITY_CAMERA_1
	const EVENT_SECURITY_CAMERA_2
	const EVENT_SECURITY_CAMERA_3
	const EVENT_SECURITY_CAMERA_4
	const EVENT_SECURITY_CAMERA_5
	const EVENT_EXPLODING_TRAP_1
	const EVENT_EXPLODING_TRAP_2
	const EVENT_EXPLODING_TRAP_3
	const EVENT_EXPLODING_TRAP_4
	const EVENT_EXPLODING_TRAP_5
	const EVENT_EXPLODING_TRAP_6
	const EVENT_EXPLODING_TRAP_7
	const EVENT_EXPLODING_TRAP_8
	const EVENT_EXPLODING_TRAP_9
	const EVENT_EXPLODING_TRAP_10
	const EVENT_EXPLODING_TRAP_11
	const EVENT_EXPLODING_TRAP_12
	const EVENT_EXPLODING_TRAP_13
	const EVENT_EXPLODING_TRAP_14
	const EVENT_EXPLODING_TRAP_15
	const EVENT_EXPLODING_TRAP_16
	const EVENT_EXPLODING_TRAP_17
	const EVENT_EXPLODING_TRAP_18
	const EVENT_EXPLODING_TRAP_19
	const EVENT_EXPLODING_TRAP_20
	const EVENT_EXPLODING_TRAP_21
	const EVENT_EXPLODING_TRAP_22
	const EVENT_LEARNED_HAIL_GIOVANNI
	const EVENT_OPENED_DOOR_TO_ROCKET_HIDEOUT_TRANSMITTER
	const EVENT_LEARNED_SLOWPOKETAIL
	const EVENT_LEARNED_RATICATE_TAIL
	const EVENT_OPENED_DOOR_TO_GIOVANNIS_OFFICE
	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_1
	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_2
	const EVENT_GOLDENROD_DEPT_STORE_B1F_LAYOUT_3
	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_BLOCKED_OFF
	const EVENT_LEFT_MONS_WITH_CONTEST_OFFICER
	const EVENT_WILLS_ROOM_ENTRANCE_CLOSED
	const EVENT_WILLS_ROOM_EXIT_OPEN
	const EVENT_KOGAS_ROOM_ENTRANCE_CLOSED
	const EVENT_KOGAS_ROOM_EXIT_OPEN
	const EVENT_BRUNOS_ROOM_ENTRANCE_CLOSED
	const EVENT_BRUNOS_ROOM_EXIT_OPEN
	const EVENT_KARENS_ROOM_ENTRANCE_CLOSED
	const EVENT_KARENS_ROOM_EXIT_OPEN
	const EVENT_LANCES_ROOM_ENTRANCE_CLOSED
	const EVENT_LANCES_ROOM_EXIT_OPEN
	const EVENT_CONTEST_OFFICER_HAS_SUN_STONE
	const EVENT_CONTEST_OFFICER_HAS_EVERSTONE
	const EVENT_CONTEST_OFFICER_HAS_GOLD_BERRY
	const EVENT_CONTEST_OFFICER_HAS_BERRY
	const EVENT_FOUGHT_HO_OH
	const EVENT_FOUGHT_LUGIA
	const EVENT_BEAT_RIVAL_IN_MT_MOON
	const EVENT_MET_BILLS_GRANDPA
	const EVENT_SHOWED_LICKITUNG_TO_BILLS_GRANDPA
	const EVENT_SHOWED_ODDISH_TO_BILLS_GRANDPA
	const EVENT_SHOWED_STARYU_TO_BILLS_GRANDPA
	const EVENT_SHOWED_GROWLITHE_VULPIX_TO_BILLS_GRANDPA
	const EVENT_SHOWED_PICHU_TO_BILLS_GRANDPA
	const EVENT_GOT_EVERSTONE_FROM_BILLS_GRANDPA
	const EVENT_GOT_LEAF_STONE_FROM_BILLS_GRANDPA
	const EVENT_GOT_WATER_STONE_FROM_BILLS_GRANDPA
	const EVENT_GOT_FIRE_STONE_FROM_BILLS_GRANDPA
	const EVENT_GOT_THUNDERSTONE_FROM_BILLS_GRANDPA
	const EVENT_LISTENED_TO_INITIAL_RADIO
; More Crystal-exclusive events in Johto
	const EVENT_WALL_OPENED_IN_HO_OH_CHAMBER
	const EVENT_WALL_OPENED_IN_KABUTO_CHAMBER
	const EVENT_WALL_OPENED_IN_OMANYTE_CHAMBER
	const EVENT_WALL_OPENED_IN_AERODACTYL_CHAMBER
	const EVENT_WELCOMED_TO_POKECOM_CENTER
	const EVENT_WADE_HAS_BERRY
	const EVENT_WADE_HAS_PSNCUREBERRY
	const EVENT_WADE_HAS_PRZCUREBERRY
	const EVENT_WADE_HAS_BITTER_BERRY
	const EVENT_WILTON_HAS_ULTRA_BALL
	const EVENT_WILTON_HAS_GREAT_BALL
	const EVENT_WILTON_HAS_POKE_BALL
	const EVENT_HOLE_IN_BURNED_TOWER
	const EVENT_FOUGHT_EUSINE
	const EVENT_KOJI_ALLOWS_YOU_PASSAGE_TO_TIN_TOWER
	const EVENT_FOUGHT_SUICUNE
	const EVENT_GOT_RAINBOW_WING
	const EVENT_HUEY_PROTEIN
	const EVENT_JOEY_HP_UP
	const EVENT_VANCE_CARBOS
	const EVENT_PARRY_IRON
	const EVENT_ERIN_CALCIUM
	const EVENT_BUENA_OFFERED_HER_PHONE_NUMBER
	const EVENT_MET_BUENA
	const EVENT_GOT_ODD_EGG
	const_skip ; unused
	const EVENT_GOT_GS_BALL_FROM_POKECOM_CENTER
; Unused: next 166 events

	const_next 999
; Trainer flags
; Swimmer F
	const EVENT_BEAT_SWIMMERF_KAYLEE
	const EVENT_BEAT_SWIMMERF_SUSIE ; unused
	const EVENT_BEAT_SWIMMERF_DENISE ; unused
	const EVENT_BEAT_SWIMMERF_KARA ; unused
	const EVENT_BEAT_SWIMMERF_WENDY ; unused
	const EVENT_BEAT_SWIMMERF_LISA ; unused
	const EVENT_BEAT_SWIMMERF_JILL ; unused
	const EVENT_BEAT_SWIMMERF_MARY ; unused
	const EVENT_BEAT_SWIMMERF_KATIE ; unused
	const EVENT_BEAT_SWIMMERF_DAWN ; unused
	const EVENT_BEAT_SWIMMERF_TARA ; unused
	const EVENT_BEAT_SWIMMERF_NICOLE ; unused
	const EVENT_BEAT_SWIMMERF_LORI ; unused
	const EVENT_BEAT_SWIMMERF_JODY ; unused
	const EVENT_BEAT_SWIMMERF_NIKKI ; unused
	const EVENT_BEAT_SWIMMERF_DIANA ; unused
	const EVENT_BEAT_SWIMMERF_BRIANA ; unused
; Bird Keeper
	const EVENT_BEAT_BIRD_KEEPER_ROD
	const EVENT_BEAT_BIRD_KEEPER_ABE
	const EVENT_BEAT_BIRD_KEEPER_BRYAN
	const EVENT_BEAT_BIRD_KEEPER_THEO
	const EVENT_BEAT_BIRD_KEEPER_TOBY ; unused
	const EVENT_BEAT_BIRD_KEEPER_DENIS ; unused
	const EVENT_BEAT_BIRD_KEEPER_VANCE ; unused
	const EVENT_BEAT_BIRD_KEEPER_HANK ; unused
	const EVENT_BEAT_BIRD_KEEPER_ROY ; unused
	const EVENT_BEAT_BIRD_KEEPER_BORIS ; unused
	const EVENT_BEAT_BIRD_KEEPER_BOB ; unused
	const EVENT_BEAT_BIRD_KEEPER_JOSE ; unused
	const EVENT_BEAT_BIRD_KEEPER_PETER ; unused
	const EVENT_BEAT_BIRD_KEEPER_JOSE2 ; unused
	const EVENT_BEAT_BIRD_KEEPER_PERRY ; unused
	const EVENT_BEAT_BIRD_KEEPER_BRET ; unused
	const EVENT_BEAT_BIRD_KEEPER_JOSE3 ; unused
	const EVENT_BEAT_BIRD_KEEPER_VANCE2 ; unused
	const EVENT_BEAT_BIRD_KEEPER_VANCE3 ; unused
; Boarder
	const EVENT_BEAT_BOARDER_RONALD
	const EVENT_BEAT_BOARDER_BRAD ; unused
	const EVENT_BEAT_BOARDER_DOUGLAS ; unused
; Photographer
	const EVENT_BEAT_PHOTOGRAPHER_JULIAN
	const EVENT_BEAT_PHOTOGRAPHER_NICO
	const EVENT_BEAT_PHOTOGRAPHER_BRIAN
	const EVENT_BEAT_PHOTOGRAPHER_TROY
	const EVENT_BEAT_PHOTOGRAPHER_JEFFREY ; unused
	const EVENT_BEAT_PHOTOGRAPHER_PING ; unused
	const EVENT_BEAT_PHOTOGRAPHER_EDMOND ; unused
	const EVENT_BEAT_PHOTOGRAPHER_NEAL ; unused
	const EVENT_BEAT_PHOTOGRAPHER_LI ; unused
; Camper
	const EVENT_BEAT_CAMPER_ROLAND
	const EVENT_BEAT_CAMPER_TODD
	const EVENT_BEAT_CAMPER_IVAN
	const EVENT_BEAT_CAMPER_ELLIOT ; unused
	const EVENT_BEAT_CAMPER_BARRY ; unused
	const EVENT_BEAT_CAMPER_LLOYD ; unused
	const EVENT_BEAT_CAMPER_DEAN ; unused
	const EVENT_BEAT_CAMPER_SID ; unused
	const EVENT_BEAT_CAMPER_HERVEY ; unused
	const EVENT_BEAT_CAMPER_DALE ; unused
	const EVENT_BEAT_CAMPER_TED ; unused
	const EVENT_BEAT_CAMPER_TODD2 ; unused
	const EVENT_BEAT_CAMPER_TODD3 ; unused
	const EVENT_BEAT_CAMPER_THOMAS ; unused
	const EVENT_BEAT_CAMPER_LEROY ; unused
	const EVENT_BEAT_CAMPER_DAVID ; unused
	const EVENT_BEAT_CAMPER_JOHN ; unused
	const EVENT_BEAT_CAMPER_JERRY ; unused
	const EVENT_BEAT_CAMPER_SPENCER ; unused
; Burglar
	const EVENT_BEAT_BURGLAR_DUNCAN
	const EVENT_BEAT_BURGLAR_EDDIE ; unused
	const EVENT_BEAT_BURGLAR_COREY ; unused
	const_skip ; unused
; Biker
	const EVENT_BEAT_BIKER_BENNY
	const EVENT_BEAT_BIKER_KAZU
	const EVENT_BEAT_BIKER_DWAYNE
	const EVENT_BEAT_BIKER_HARRIS ; unused
	const EVENT_BEAT_BIKER_ZEKE ; unused
	const EVENT_BEAT_BIKER_CHARLES ; unused
	const EVENT_BEAT_BIKER_RILEY ; unused
	const EVENT_BEAT_BIKER_JOEL ; unused
	const EVENT_BEAT_BIKER_GLENN ; unused
; Couple
	const EVENT_BEAT_COUPLE_JO_AND_JOE
; Psychic
	const EVENT_BEAT_PSYCHIC_NATHAN
	const EVENT_BEAT_PSYCHIC_FRANKLIN
	const EVENT_BEAT_PSYCHIC_HERMAN ; unused
	const EVENT_BEAT_PSYCHIC_FIDEL ; unused
	const EVENT_BEAT_PSYCHIC_GREG ; unused
	const EVENT_BEAT_PSYCHIC_NORMAN ; unused
	const EVENT_BEAT_PSYCHIC_MARK ; unused
	const EVENT_BEAT_PSYCHIC_PHIL ; unused
	const EVENT_BEAT_PSYCHIC_RICHARD ; unused
	const EVENT_BEAT_PSYCHIC_GILBERT ; unused
	const EVENT_BEAT_PSYCHIC_JARED ; unused
	const EVENT_BEAT_PSYCHIC_RODNEY ; unused
; Firebreather
	const EVENT_BEAT_FIREBREATHER_OTIS
	const EVENT_BEAT_FIREBREATHER_DICK
	const EVENT_BEAT_FIREBREATHER_NED
	const EVENT_BEAT_FIREBREATHER_BURT
	const EVENT_BEAT_FIREBREATHER_BILL ; unused
	const EVENT_BEAT_FIREBREATHER_WALT ; unused
	const EVENT_BEAT_FIREBREATHER_RAY ; unused
	const EVENT_BEAT_FIREBREATHER_LYLE ; unused
; Fisher
	const EVENT_BEAT_FISHER_JUSTIN
	const EVENT_BEAT_FISHER_RALPH
	const EVENT_BEAT_FISHER_ARNOLD
	const EVENT_BEAT_FISHER_GORO
	const EVENT_BEAT_FISHER_HENRY
	const EVENT_BEAT_FISHER_MARVIN
	const EVENT_BEAT_FISHER_TULLY
	const EVENT_BEAT_FISHER_ANDRE
	const EVENT_BEAT_FISHER_RAYMOND ; unused
	const EVENT_BEAT_FISHER_WILTON ; unused
	const EVENT_BEAT_FISHER_EDGAR ; unused
	const EVENT_BEAT_FISHER_JONAH ; unused
	const EVENT_BEAT_FISHER_MARTIN ; unused
	const EVENT_BEAT_FISHER_STEPHEN ; unused
	const EVENT_BEAT_FISHER_BARNEY ; unused
	const EVENT_BEAT_FISHER_RALPH2 ; unused
	const EVENT_BEAT_FISHER_RALPH3 ; unused
	const EVENT_BEAT_FISHER_TULLY2 ; unused
	const EVENT_BEAT_FISHER_TULLY3 ; unused
	const EVENT_BEAT_FISHER_WILTON2 ; unused
	const EVENT_BEAT_FISHER_SCOTT ; unused
	const EVENT_BEAT_FISHER_WILTON3 ; unused
; Twins
	const EVENT_BEAT_TWINS_AMY_AND_MAY
	const EVENT_BEAT_TWINS_ANN_AND_ANNE ; unused
	const EVENT_BEAT_TWINS_ANN_AND_ANNE2 ; unused
	const EVENT_BEAT_TWINS_AMY_AND_MAY2 ; unused
	const EVENT_BEAT_TWINS_JO_AND_ZOE ; unused
	const EVENT_BEAT_TWINS_JO_AND_ZOE2 ; unused
	const EVENT_BEAT_TWINS_MEG_AND_PEG ; unused
	const EVENT_BEAT_TWINS_MEG_AND_PEG2 ; unused
; Worker
	const EVENT_BEAT_WORKER_Q
	const EVENT_BEAT_WORKER_KIP
	const EVENT_BEAT_WORKER_ALAN
	const EVENT_BEAT_WORKER_JOHNNY ; unused
	const EVENT_BEAT_WORKER_DANNY ; unused
	const EVENT_BEAT_WORKER_TOMMY ; unused
	const EVENT_BEAT_WORKER_DUDLEY ; unused
	const EVENT_BEAT_WORKER_JOE ; unused
	const EVENT_BEAT_WORKER_BILLY ; unused
	const EVENT_BEAT_WORKER_CHAD ; unused
	const EVENT_BEAT_WORKER_NATE ; unused
	const EVENT_BEAT_WORKER_RICKY ; unused
	const EVENT_BEAT_WORKER_JACK2 ; unused
	const EVENT_BEAT_WORKER_JACK3 ; unused
	const EVENT_BEAT_WORKER_ALAN2 ; unused
	const EVENT_BEAT_WORKER_ALAN3 ; unused
	const EVENT_BEAT_WORKER_CHAD2 ; unused
	const EVENT_BEAT_WORKER_CHAD3 ; unused
; Picnicker
	const EVENT_BEAT_PICNICKER_LIZZY
	const EVENT_BEAT_PICNICKER_GINA
	const EVENT_BEAT_PICNICKER_BROOKE
	const EVENT_BEAT_PICNICKER_KIM
	const EVENT_BEAT_PICNICKER_CINDY
	const EVENT_BEAT_PICNICKER_HOPE ; unused
	const EVENT_BEAT_PICNICKER_SHARON ; unused
	const EVENT_BEAT_PICNICKER_DEBRA ; unused
	const EVENT_BEAT_PICNICKER_GINA2 ; unused
	const EVENT_BEAT_PICNICKER_ERIN ; unused
	const EVENT_BEAT_PICNICKER_LIZ2 ; unused
	const EVENT_BEAT_PICNICKER_LIZ3 ; unused
	const EVENT_BEAT_PICNICKER_HEIDI ; unused
	const EVENT_BEAT_PICNICKER_EDNA ; unused
	const EVENT_BEAT_PICNICKER_GINA3 ; unused
	const EVENT_BEAT_PICNICKER_TIFFANY2 ; unused
	const EVENT_BEAT_PICNICKER_TIFFANY3 ; unused
	const EVENT_BEAT_PICNICKER_ERIN2 ; unused
	const EVENT_BEAT_PICNICKER_TANYA ; unused
	const EVENT_BEAT_PICNICKER_TIFFANY ; unused
	const EVENT_BEAT_PICNICKER_ERIN3 ; unused
; Guitarist
	const EVENT_BEAT_GUITARIST_CLYDE
	const EVENT_BEAT_GUITARIST_VINCENT ; unused
; Juggler
	const EVENT_BEAT_JUGGLER_IRWIN
	const EVENT_BEAT_JUGGLER_FRITZ ; unused
	const EVENT_BEAT_JUGGLER_HORTON ; unused
	const EVENT_BEAT_JUGGLER_IRWIN2 ; unused
	const EVENT_BEAT_JUGGLER_IRWIN3 ; unused
; Gentleman
	const EVENT_BEAT_GENTLEMAN_NICK_B
	const EVENT_BEAT_GENTLEMAN_JORDANP
	const EVENT_BEAT_GENTLEMAN_GREGORY ; unused
	const EVENT_BEAT_GENTLEMAN_VIRGIL ; unused
	const EVENT_BEAT_GENTLEMAN_ALFRED ; unused
; IT Guy
	const EVENT_BEAT_IT_GUY_MIKE_B
	const EVENT_BEAT_IT_GUY_MITCH ; unused
	const EVENT_BEAT_IT_GUY_JED ; unused
	const EVENT_BEAT_IT_GUY_MARC ; unused
	const EVENT_BEAT_IT_GUY_RICH ; unused
; Blackbelt
	const EVENT_BEAT_BLACKBELT_DANIEL
	const EVENT_BEAT_BLACKBELT_YOSHI
	const EVENT_BEAT_BLACKBELT_KENJI3
	const EVENT_BEAT_BLACKBELT_LAO ; unused
	const EVENT_BEAT_BLACKBELT_NOB ; unused
	const EVENT_BEAT_BLACKBELT_KIYO ; unused
	const EVENT_BEAT_BLACKBELT_LUNG ; unused
	const EVENT_BEAT_BLACKBELT_KENJI ; unused
	const EVENT_BEAT_BLACKBELT_WAI ; unused
; White Girl
	const EVENT_BEAT_WHITE_GIRL_AIMEE
	const EVENT_BEAT_WHITE_GIRL_TAYLOR
	const EVENT_BEAT_WHITE_GIRL_JULIE
	const EVENT_BEAT_WHITE_GIRL_JACLYN
	const EVENT_BEAT_WHITE_GIRL_BRENDA
	const EVENT_BEAT_WHITE_GIRL_BOOZER
	const EVENT_BEAT_WHITE_GIRL_CAROLINE ; unused
	const EVENT_BEAT_WHITE_GIRL_CARLENE ; unused
	const EVENT_BEAT_WHITE_GIRL_JESSICA ; unused
	const EVENT_BEAT_WHITE_GIRL_RACHAEL ; unused
	const EVENT_BEAT_WHITE_GIRL_ANGELICA ; unused
	const EVENT_BEAT_WHITE_GIRL_KENDRA ; unused
	const EVENT_BEAT_WHITE_GIRL_VERONICA ; unused
	const EVENT_BEAT_WHITE_GIRL_JULIA ; unused
	const EVENT_BEAT_WHITE_GIRL_THERESA ; unused
	const EVENT_BEAT_WHITE_GIRL_VALERIE ; unused
; Gym Leaders
	const EVENT_BEAT_SARAH1
	const EVENT_BEAT_MORTY ; unused
	const EVENT_BEAT_JASMINE ; unused
	const EVENT_BEAT_CHUCK ; unused
	const EVENT_BEAT_PRYCE ; unused
	const EVENT_BEAT_LEE1
	const EVENT_BEAT_MISTY ; unused
	const EVENT_BEAT_ERIKA ; unused
	const EVENT_BEAT_JANINE ; unused
	const EVENT_BEAT_SABRINA ; unused
	const EVENT_BEAT_BLAINE ; unused
	const EVENT_BEAT_BLUE ; unused
; Furries
	const EVENT_BEAT_FURRY_VICTORIA
	const EVENT_BEAT_FURRY_HOLLOWAY
; Jordan
	const EVENT_BEAT_RANCHER_JORDAN
	const EVENT_BEAT_JORDAN_2
; Loafers
	const EVENT_BEAT_SAM_1
; Pastors
	const EVENT_BEAT_PASTOR_JOELEO
; Supervisors
	const EVENT_BEAT_SUPERVISOR_JOSH
	const EVENT_BEAT_SUPERVISOR_STEV
	const EVENT_BEAT_SUPERVISOR_SCOT
; GRAMPS
	const EVENT_BEAT_GRAMPS_WILLIS
	const EVENT_BEAT_GRAMPS_DEREK ; unused
	const EVENT_BEAT_GRAMPS_ROBERT ; unused
	const EVENT_BEAT_GRAMPS_JOSHUA ; unused
	const EVENT_BEAT_GRAMPS_CARTER ; unused
	const EVENT_BEAT_GRAMPS_TREVOR ; unused
	const EVENT_BEAT_GRAMPS_BRANDON ; unused
	const EVENT_BEAT_GRAMPS_JEREMY ; unused
	const EVENT_BEAT_GRAMPS_COLIN ; unused
	const EVENT_BEAT_GRAMPS_DEREK2 ; unused
	const EVENT_BEAT_GRAMPS_DEREK3 ; unused
	const EVENT_BEAT_GRAMPS_ALEX ; unused
; GRANNY
	const EVENT_BEAT_GRANNY_BEVERLY
	const EVENT_BEAT_GRANNY_RUTH ; unused
	const EVENT_BEAT_GRANNY_BEVERLY2 ; unused
	const EVENT_BEAT_GRANNY_BEVERLY3 ; unused
	const EVENT_BEAT_GRANNY_GEORGIA ; unused
; Kimono Girl
	const_skip ; unused
	const EVENT_BEAT_KIMONO_GIRL_SUI
	const EVENT_BEAT_KIMONO_GIRL_AKANE
	const EVENT_BEAT_KIMONO_GIRL_RIKO
	const EVENT_BEAT_KIMONO_GIRL_KIMI
	const EVENT_BEAT_KIMONO_GIRL_KARI
	const EVENT_BEAT_KIMONO_GIRL_HIKA
	const EVENT_BEAT_KIMONO_GIRL_HANA
	const EVENT_BEAT_KIMONO_GIRL_SEN
	const EVENT_BEAT_KIMONO_GIRL_HACHI
; Weirdo
	const EVENT_BEAT_WEIRDO_NICK
	const EVENT_BEAT_WEIRDO_ANDREW
	const EVENT_BEAT_WEIRDO_CALVIN
	const EVENT_BEAT_WEIRDO_JACK_SIMON
	const EVENT_BEAT_WEIRDO_LOGAN
	const EVENT_BEAT_WEIRDO_BRENT
	const EVENT_BEAT_WEIRDO_RON ; unused
	const EVENT_BEAT_WEIRDO_ETHAN ; unused
	const EVENT_BEAT_WEIRDO_BRENT2 ; unused
	const EVENT_BEAT_WEIRDO_BRENT3 ; unused
	const EVENT_BEAT_WEIRDO_ISSAC ; unused
	const EVENT_BEAT_WEIRDO_DONALD ; unused
	const EVENT_BEAT_WEIRDO_ZACH ; unused
; GruntM
	const EVENT_BEAT_GLITCH_1
	const EVENT_BEAT_GLITCH_2
	const EVENT_BEAT_GLITCH_3
	const EVENT_BEAT_GLITCH_4
	const EVENT_BEAT_GLITCH_5
	const EVENT_BEAT_GLITCH_6
	const EVENT_BEAT_GLITCH_7 ; unused
	const EVENT_BEAT_GLITCH_8 ; unused
	const EVENT_BEAT_GLITCH_9 ; unused
	const EVENT_BEAT_GLITCH_10 ; unused
	const EVENT_BEAT_GLITCH_11 ; unused
	const EVENT_BEAT_GLITCH_12 ; unused
	const EVENT_BEAT_GLITCH_13 ; unused
	const EVENT_BEAT_GLITCH_14 ; unused
	const EVENT_BEAT_GLITCH_15 ; unused
	const EVENT_BEAT_GLITCH_16 ; unused
	const EVENT_BEAT_GLITCH_17 ; unused
	const EVENT_BEAT_GLITCH_18 ; unused
	const EVENT_BEAT_GLITCH_19 ; unused
	const EVENT_BEAT_GLITCH_20 ; unused
	const EVENT_BEAT_GLITCH_21 ; unused
; Ruin Maniac
	const EVENT_BEAT_RUIN_MANIAC_NIEL
	const EVENT_BEAT_RUIN_MANIAC_ELVIN
; Safarihid
	const EVENT_BEAT_SAFARI_INDY
; Tamer
	const EVENT_BEAT_TAMER_RINGLE
; Goron
	const EVENT_BEAT_GORON_DARU
	const EVENT_BEAT_GORON_KOGO
	const EVENT_BEAT_GORON_ZUDO
	const EVENT_BEAT_GORON_TODO
	const EVENT_BEAT_GORON_GRAMRO
; Feral Child
	const EVENT_BEAT_FERAL_CHILD_GAU
; Battle Girl
	const EVENT_BEAT_BATTLE_GIRL_VIDEL
; Karate King
	const EVENT_BEAT_KARATE_KING_JET
; Lass
	const EVENT_BEAT_LASS_CARRIE
	const EVENT_BEAT_LASS_BRIDGET
	const EVENT_BEAT_LASS_JASMINE
	const EVENT_BEAT_LASS_KRISE ; unused
	const EVENT_BEAT_LASS_CONNIE ; unused
	const EVENT_BEAT_LASS_LINDA ; unused
	const EVENT_BEAT_LASS_LAURA ; unused
	const EVENT_BEAT_LASS_SHANNON ; unused
	const EVENT_BEAT_LASS_MICHELLE ; unused
	const EVENT_BEAT_LASS_DANA ; unused
	const EVENT_BEAT_LASS_ELLEN ; unused
	const EVENT_BEAT_LASS_CONNIE2 ; unused
	const EVENT_BEAT_LASS_CONNIE3 ; unused
	const EVENT_BEAT_LASS_DANA2 ; unused
; Hiker
	const EVENT_BEAT_HIKER_COURTNEY
	const EVENT_BEAT_HIKER_HORACE
	const EVENT_BEAT_HIKER_PHILLIP
	const EVENT_BEAT_HIKER_LEONARD
	const EVENT_BEAT_HIKER_ANTHONY
	const EVENT_BEAT_HIKER_BENJAMIN
	const EVENT_BEAT_HIKER_ERIK
	const EVENT_BEAT_HIKER_MICHAEL
	const EVENT_BEAT_HIKER_PARRY
	const EVENT_BEAT_HIKER_TIMOTHY ; unused
	const EVENT_BEAT_HIKER_BAILEY ; unused
	const EVENT_BEAT_HIKER_ANTHONY3 ; unused
	const EVENT_BEAT_HIKER_TIM ; unused
	const EVENT_BEAT_HIKER_NOLAND ; unused
	const EVENT_BEAT_HIKER_SIDNEY ; unused
	const EVENT_BEAT_HIKER_KENNY ; unused
	const EVENT_BEAT_HIKER_JIM2 ; unused
	const EVENT_BEAT_HIKER_DANIEL ; unused
	const EVENT_BEAT_HIKER_PARRY2 ; unused
	const EVENT_BEAT_HIKER_PARRY3 ; unused
; Bug Catcher
	const EVENT_BEAT_BUG_CATCHER_DON
	const EVENT_BEAT_BUG_CATCHER_JIM
	const EVENT_BEAT_BUG_CATCHER_ED
	const EVENT_BEAT_BUG_CATCHER_WADE
	const EVENT_BEAT_BUG_CATCHER_BENNY
	const EVENT_BEAT_BUG_CATCHER_AL
	const EVENT_BEAT_BUG_CATCHER_JOSH
; Bug Maniac
	const EVENT_BEAT_BUG_MANIAC_ARNIE
	const EVENT_BEAT_BUG_MANIAC_KEN ; unused
	const EVENT_BEAT_BUG_MANIAC_WADE2 ; unused
	const EVENT_BEAT_BUG_MANIAC_WADE3 ; unused
	const EVENT_BEAT_BUG_MANIAC_DOUG ; unused
	const EVENT_BEAT_BUG_MANIAC_ARNIE2 ; unused
	const EVENT_BEAT_BUG_MANIAC_ARNIE3 ; unused
; Officer
	const EVENT_BEAT_OFFICER_KEITH ; unused
	const EVENT_BEAT_OFFICER_DIRK ; unused
; CooltrainerM
	const EVENT_BEAT_COOLTRAINERM_NICKY
	const EVENT_BEAT_COOLTRAINERM_AARON
	const EVENT_BEAT_COOLTRAINERM_PAUL ; unused
	const EVENT_BEAT_COOLTRAINERM_CODY ; unused
	const EVENT_BEAT_COOLTRAINERM_MIKE ; unused
	const EVENT_BEAT_COOLTRAINERM_GAVEN2 ; unused
	const EVENT_BEAT_COOLTRAINERM_GAVEN3 ; unused
	const EVENT_BEAT_COOLTRAINERM_RYAN ; unused
	const EVENT_BEAT_COOLTRAINERM_JAKE ; unused
	const EVENT_BEAT_COOLTRAINERM_GAVEN ; unused
	const EVENT_BEAT_COOLTRAINERM_BLAKE ; unused
	const EVENT_BEAT_COOLTRAINERM_BRIAN ; unused
	const EVENT_BEAT_COOLTRAINERM_ERICK ; unused
	const EVENT_BEAT_COOLTRAINERM_ANDY ; unused
	const EVENT_BEAT_COOLTRAINERM_TYLER ; unused
	const EVENT_BEAT_COOLTRAINERM_SEAN ; unused
	const EVENT_BEAT_COOLTRAINERM_KEVIN ; unused
	const EVENT_BEAT_COOLTRAINERM_STEVE ; unused
	const EVENT_BEAT_COOLTRAINERM_ALLEN ; unused
; CooltrainerF
	const EVENT_BEAT_COOLTRAINERF_GWEN
	const EVENT_BEAT_COOLTRAINERF_LOIS
	const EVENT_BEAT_COOLTRAINERF_FRAN ; unused
	const EVENT_BEAT_COOLTRAINERF_LOLA ; unused
	const EVENT_BEAT_COOLTRAINERF_KATE ; unused
	const EVENT_BEAT_COOLTRAINERF_IRENE ; unused
	const EVENT_BEAT_COOLTRAINERF_KELLY ; unused
	const EVENT_BEAT_COOLTRAINERF_JOYCE ; unused
	const EVENT_BEAT_COOLTRAINERF_BETH ; unused
	const EVENT_BEAT_COOLTRAINERF_REENA ; unused
	const EVENT_BEAT_COOLTRAINERF_MEGAN ; unused
	const EVENT_BEAT_COOLTRAINERF_BETH2 ; unused
	const EVENT_BEAT_COOLTRAINERF_CAROL ; unused
	const EVENT_BEAT_COOLTRAINERF_QUINN ; unused
	const EVENT_BEAT_COOLTRAINERF_EMMA ; unused
	const EVENT_BEAT_COOLTRAINERF_CYBIL ; unused
	const EVENT_BEAT_COOLTRAINERF_JENN ; unused
	const EVENT_BEAT_COOLTRAINERF_BETH3 ; unused
	const EVENT_BEAT_COOLTRAINERF_REENA2 ; unused
	const EVENT_BEAT_COOLTRAINERF_REENA3 ; unused
; CEO
	const EVENT_BEAT_CEO_LONGO
	const EVENT_BEAT_ROCKET_EXECUTIVEM_2 ; unused
	const EVENT_BEAT_ROCKET_EXECUTIVEM_3 ; unused
	const EVENT_BEAT_ROCKET_EXECUTIVEM_4 ; unused
; Sailor
	const EVENT_BEAT_SAILOR_EUGENE ; unused
	const EVENT_BEAT_SAILOR_HUEY ; unused
	const EVENT_BEAT_SAILOR_TERRELL ; unused
	const EVENT_BEAT_SAILOR_KENT ; unused
	const EVENT_BEAT_SAILOR_ERNEST ; unused
	const EVENT_BEAT_SAILOR_JEFF ; unused
	const EVENT_BEAT_SAILOR_GARRETT ; unused
	const EVENT_BEAT_SAILOR_KENNETH ; unused
	const EVENT_BEAT_SAILOR_STANLY ; unused
	const EVENT_BEAT_SAILOR_HARRY ; unused
	const EVENT_BEAT_SAILOR_HUEY2 ; unused
	const EVENT_BEAT_SAILOR_HUEY3 ; unused
; Hex Maniac
	const EVENT_BEAT_HEX_MANIAC_HANNA
; Pyros
	const EVENT_BEAT_PYRO_DENA
	const EVENT_BEAT_PYRO_MANNY
; Artists
	const EVENT_BEAT_ARTIST_ANGELO
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Medium
	const EVENT_BEAT_MEDIUM_MARTHA
	const EVENT_BEAT_MEDIUM_GRACE
	const EVENT_BEAT_MEDIUM_WELL
	const EVENT_BEAT_MEDIUM_MARGRET ; unused
	const EVENT_BEAT_MEDIUM_ETHEL ; unused
	const EVENT_BEAT_MEDIUM_REBECCA ; unused
	const EVENT_BEAT_MEDIUM_DORIS ; unused
; Skier
	const EVENT_BEAT_SKIER_ROXANNE
	const EVENT_BEAT_SKIER_CLARISSA ; unused
; SwimmerM
	const EVENT_BEAT_SWIMMERM_HAROLD ; unused
	const EVENT_BEAT_SWIMMERM_SIMON ; unused
	const EVENT_BEAT_SWIMMERM_RANDALL ; unused
	const EVENT_BEAT_SWIMMERM_CHARLIE ; unused
	const EVENT_BEAT_SWIMMERM_GEORGE ; unused
	const EVENT_BEAT_SWIMMERM_BERKE ; unused
	const EVENT_BEAT_SWIMMERM_KIRK ; unused
	const EVENT_BEAT_SWIMMERM_MATHEW ; unused
	const EVENT_BEAT_SWIMMERM_HAL ; unused
	const EVENT_BEAT_SWIMMERM_PATON ; unused
	const EVENT_BEAT_SWIMMERM_DARYL ; unused
	const EVENT_BEAT_SWIMMERM_WALTER ; unused
	const EVENT_BEAT_SWIMMERM_TONY ; unused
	const EVENT_BEAT_SWIMMERM_JEROME ; unused
	const EVENT_BEAT_SWIMMERM_TUCKER ; unused
	const EVENT_BEAT_SWIMMERM_RICK ; unused
	const EVENT_BEAT_SWIMMERM_CAMERON ; unused
	const EVENT_BEAT_SWIMMERM_SETH ; unused
	const EVENT_BEAT_SWIMMERM_JAMES ; unused
	const EVENT_BEAT_SWIMMERM_LEWIS ; unused
	const EVENT_BEAT_SWIMMERM_PARKER ; unused
; Youngster
	const EVENT_BEAT_YOUNGSTER_JOEY
	const EVENT_BEAT_YOUNGSTER_MIKEY
	const EVENT_BEAT_YOUNGSTER_ALBERT
	const EVENT_BEAT_YOUNGSTER_GORDON ; unused
	const EVENT_BEAT_YOUNGSTER_SAMUEL ; unused
	const EVENT_BEAT_YOUNGSTER_IAN ; unused
	const EVENT_BEAT_YOUNGSTER_JOEY2 ; unused
	const EVENT_BEAT_YOUNGSTER_JOEY3 ; unused
	const EVENT_BEAT_YOUNGSTER_WARREN ; unused
	const EVENT_BEAT_YOUNGSTER_JIMMY ; unused
	const EVENT_BEAT_YOUNGSTER_OWEN ; unused
	const EVENT_BEAT_YOUNGSTER_JASON ; unused
; Teacher
	const EVENT_BEAT_TEACHER_COLETTE
	const EVENT_BEAT_TEACHER_JIN_YANG
	const EVENT_BEAT_TEACHER_SHIRLEY ; unused
; Elite Four and Champion
	const EVENT_BEAT_ELITE_4_WILL ; unused
	const EVENT_BEAT_ELITE_4_KOGA ; unused
	const EVENT_BEAT_ELITE_4_BRUNO ; unused
	const EVENT_BEAT_ELITE_4_KAREN ; unused
	const EVENT_BEAT_CHAMPION_LANCE ; unused
; Crystal-exclusive trainer flags
	const EVENT_BEAT_BUG_CATCHER_WAYNE ; unused
	const EVENT_BEAT_WHITE_GIRL_OLIVIA ; unused
; Ball Brian
	const EVENT_BEAT_BALL_BRIAN_1
	const EVENT_BEAT_BALL_BRIAN_2
	const EVENT_BEAT_BALL_BRIAN_3
	const EVENT_BEAT_BALL_BRIAN_4
	const EVENT_BEAT_BALL_BRIAN_5
; Tree Brian
	const EVENT_BEAT_TREE_BRIAN_1
	const EVENT_BEAT_TREE_BRIAN_2
	const EVENT_BEAT_TREE_BRIAN_3
	const EVENT_BEAT_TREE_BRIAN_4
; Rock Brian
	const EVENT_BEAT_ROCK_BRIAN_1
	const EVENT_BEAT_ROCK_BRIAN_2
	const EVENT_BEAT_ROCK_BRIAN_3
; Mad Dog Brian
	const EVENT_BEAT_MAD_DOG_BRIAN_1
	const EVENT_BEAT_MAD_DOG_BRIANEON
	const_skip
; Hero of Time
	const EVENT_BEAT_AWAKENING_BEACH_LINK
	const EVENT_BEAT_GLITCH_LINK
	const EVENT_BEAT_DUNGEON_LINK
; Keyblader
	const EVENT_BEAT_AWAKENING_BEACH_SORA
	const EVENT_BEAT_KEYBLADER_OAK
; Ghost
	const EVENT_BEAT_GHOST_CLAY
; Undead
	const EVENT_BEAT_UNDEAD_CLAY
; Brian64
	const EVENT_BEAT_BRIAN_64_1
	const EVENT_BEAT_BRIAN_64_2
; BugBrian
	const EVENT_BEAT_BUG_BRIAN_1
	const EVENT_BEAT_BUG_BRIAN_2
; Other One-offs
	const EVENT_BEAT_RYAN1
	const EVENT_BEAT_MADDIE1
; Ruffians
	const EVENT_BEAT_RUFFIAN_GRENDO
	const EVENT_BEAT_RUFFIAN_BRIAN
; Brian M
	const EVENT_BEAT_BRIAN_M_1
	const EVENT_BEAT_BRIAN_M_2
	const EVENT_BEAT_BRIAN_M_3
; Brian F
	const EVENT_BEAT_BRIAN_F_1
	const EVENT_BEAT_BRIAN_F_2
; Sightseer M
	const EVENT_BEAT_SIGHTSEER_JACK
; Sightseer F
	const EVENT_BEAT_SIGHTSEER_JILL
; Waifu
	const EVENT_BEAT_WAIFU_MIKU
; ENGINEER
	const EVENT_BEAT_ENGINEER_DONNY
; MAD SCIENTIST
	const EVENT_BEAT_MAD_SCIENTIST_BROWN
; Other Brians
	const EVENT_BEAT_MER_BRIAN
; Moblins
	const EVENT_BEAT_MOBLIN_1
	const EVENT_BEAT_MOBLIN_2
	const EVENT_BEAT_MOBLIN_3
	const EVENT_BEAT_MOBLIN_4
	const EVENT_BEAT_MOBLIN_5
	const EVENT_BEAT_MOBLIN_WILKEN
	const EVENT_BEAT_MOBLIN_6
	const EVENT_BEAT_MOBLIN_7
	const EVENT_BEAT_MOBLIN_8
	const EVENT_BEAT_MOBLIN_9
	const EVENT_BEAT_MOBLIN_10
	const EVENT_BEAT_MOBLIN_11
; Detective M
	const EVENT_BEAT_DETECTIVE_GUM
; Detective F
	const EVENT_BEAT_DETECTIVE_JANE
; Skater Boys
	const EVENT_BEAT_SKATER_BOY_TONY
; Casey
	const EVENT_BEAT_CASEY_1
; Other
	const EVENT_BEAT_OCTOROK_9
	const EVENT_BEAT_OCTOROK_10
	const EVENT_BEAT_OCTOROK_11
	const EVENT_BEAT_OCTOROK_12
	const EVENT_BEAT_OCTOROK_13
	const EVENT_BEAT_ARMOS_1
	const EVENT_BEAT_ARMOS_2
	const EVENT_BEAT_ARMOS_3
	const EVENT_BEAT_ARMOS_4
	const EVENT_BEAT_OWL_BRIAN
	const EVENT_BEAT_MER_MARTHA
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.
; Johto itemballs
	const EVENT_BURGELA_POKEBALL
	const EVENT_PORYGON_POKEBALL
	const EVENT_SPIRRIP_POKEBALL
	const EVENT_AWAKENING_LAB_POTIONS
	const EVENT_AWAKENING_LAB_POKEBALLS
	const EVENT_ROUTE_A_GREAT_BALL
	const EVENT_ROUTE_A_TM01
	const EVENT_ROUTE_A_SUPER_POTION
	const EVENT_NORTHERNFOREST_TINY_MUSHROOM_1
	const EVENT_NORTHERNFOREST_TINY_MUSHROOM_2
	const EVENT_NORTHERNFOREST_BIG_MUSHROOM_1
	const EVENT_NORTHERNFOREST_BIG_MUSHROOM_2
	const EVENT_NORTHERNFOREST_ELIXER
	const EVENT_NORTHERNFOREST_FULL_HEAL
	const EVENT_ROUTE_B_ESCAPE_ROPE
	const EVENT_ROUTE_B_RARE_CANDY
	const EVENT_CEMETARY_MAX_REVIVE
	const EVENT_CEMETARY_NUGGET
	const EVENT_METROID_INTRO_MAX_ELIXER
	const EVENT_UNIVERCITY_MART_B1F_FULL_RESTORE
	const EVENT_UNIVERCITY_MART_B1F_ULTRA_BALL
	const EVENT_UNIVERCITY_MART_B1F_HP_UP
	const EVENT_ROUTE_C_ULTRA_BALL
	const EVENT_ROUTE_C_PARLYZ_HEAL
	const EVENT_ROUTE_C_GREAT_BALL
	const EVENT_ROUTE_C_X_ATTACK
	const EVENT_ROUTE_D_DIRE_HIT
	const EVENT_ROUTE_D_REVIVE
	const EVENT_EEVEE_RANCH_HIVES_X_SPECIAL
	const EVENT_UNION_CAVE_1F_AWAKENING
	const EVENT_UNION_CAVE_B1F_TM_SWIFT
	const EVENT_ROUTE_E_X_DEFEND
	const EVENT_ROUTE_E_ELIXER
	const EVENT_JUNGLE_HYPER_POTION
	const EVENT_JUNGLE_TM_DIG
	const EVENT_JUNGLE_ETHER
	const EVENT_JUNGLE_RARE_CANDY
	const EVENT_JUNGLE_SUPER_REPEL
	const EVENT_ROUTE_G_SUPER_POTION
	const EVENT_ROUTE_G_HYPER_POTION
	const EVENT_ROUTE_G_NUGGET
	const EVENT_ROUTE_G_METROID_CAVE_FULL_RESTORE
	const EVENT_ROUTE_G_METROID_CAVE_TM_ENERGY_BALL
	const EVENT_VOLCANO_INTERIOR_1F_GUARD_SPEC
	const EVENT_VOLCANO_INTERIOR_1F_FIRE_STONE
	const EVENT_VOLCANO_INTERIOR_1F_PROTEIN
	const EVENT_VOLCANO_INTERIOR_1F_X_SPECIAL
	const EVENT_VOLCANO_INTERIOR_2F_FULL_HEAL
	const EVENT_VOLCANO_INTERIOR_2F_TM_ROCKSLIDE
	const EVENT_VOLCANO_INTERIOR_2F_REVIVE
	const EVENT_GOLDENROD_UNDERGROUND_COIN_CASE
	const EVENT_VOLCANO_INTERIOR_3F_SMOKE_BALL
	const EVENT_VOLCANO_INTERIOR_3F_CHARCOAL
	const EVENT_VOLCANO_INTERIOR_3F_ETHER
	const EVENT_VOLCANO_INTERIOR_3F_HALL_SOFT_SAND
	const EVENT_VOLCANO_INTERIOR_4F_BURN_HEAL
	const EVENT_VOLCANO_INTERIOR_4F_ULTRA_BALL
	const EVENT_VOLCANO_INTERIOR_4F_MAX_ETHER
	const EVENT_VOLCANO_INTERIOR_4F_REVIVE
	const EVENT_GOT_TM24_IRON_HEAD
	const EVENT_VOLCANO_INTERIOR_5F_HALL_REVIVE
	const EVENT_VOLCANO_INTERIOR_B1F_ESCAPE_ROPE
	const EVENT_VOLCANO_INTERIOR_B1F_MAX_REVIVE
	const EVENT_VOLCANO_INTERIOR_B1F_HYPER_POTION
	const EVENT_GOT_TM25_MOONBLAST
	const EVENT_VOLCANO_INTERIOR_6F_MAX_POTION
	const EVENT_VOLCANO_INTERIOR_6F_RARE_CANDY
	const EVENT_GOT_TM32_PSYCHIC
	const EVENT_VOLCANO_INTERIOR_6F_HALL_DRAGON_SCALE
	const EVENT_VOLCANO_INTERIOR_6F_HALL_ELIXER
	const EVENT_GOT_TM01_BITE
	const EVENT_VOLCANO_EXTERIOR_HYPER_POTION
	const EVENT_VOLCANO_EXTERIOR_CARBOS
	const EVENT_GOT_HM07_WATERFALL
	const EVENT_VOLCANO_INTERIOR_5F_PP_UP
	const EVENT_VOLCANO_INTERIOR_5F_IRON
	const EVENT_VOLCANO_INTERIOR_5F_FULL_HEAL
	const EVENT_VOLCANO_EXTERIOR_MAX_POTION
	const EVENT_ICE_PATH_B2F_BLACKTHORN_SIDE_TM_REST
	const EVENT_ICE_PATH_B3F_NEVERMELTICE
	const EVENT_WHIRL_ISLAND_NE_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_SW_ULTRA_BALL
	const EVENT_AWAKENING_BEACH_2_FULL_RESTORE
	const EVENT_AWAKENING_BEACH_2_CARBOS
	const EVENT_AWAKENING_BEACH_2_CALCIUM
	const EVENT_AWAKENING_BEACH_2_NUGGET
	const EVENT_AWAKENING_BEACH_2_RARE_CANDY
	const EVENT_AWAKENING_BEACH_2_SHADOW_BALL
	const EVENT_WHIRL_ISLAND_B2F_MAX_REVIVE
	const EVENT_WHIRL_ISLAND_B2F_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_PROTEIN
	const EVENT_SILVER_CAVE_ROOM_1_ESCAPE_ROPE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_MAX_REVIVE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_FULL_RESTORE
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_POTION
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_FULL_HEAL
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_HYPER_POTION
	const EVENT_DARK_CAVE_BLACKTHORN_ENTRANCE_REVIVE
	const EVENT_DARK_CAVE_BLACKTHORN_ENTRANCE_TM_SNORE
	const EVENT_VICTORY_ROAD_TM_EARTHQUAKE
	const EVENT_VICTORY_ROAD_MAX_REVIVE
	const EVENT_VICTORY_ROAD_FULL_RESTORE
	const EVENT_VICTORY_ROAD_FULL_HEAL
	const EVENT_VICTORY_ROAD_HP_UP
	const EVENT_DRAGONS_DEN_B1F_DRAGON_FANG
	const EVENT_TOHJO_FALLS_MOON_STONE
	const EVENT_ROUTE_26_MAX_ELIXER
	const EVENT_ROUTE_27_TM_SOLARBEAM
	const EVENT_ROUTE_27_RARE_CANDY
	const EVENT_ROUTE_29_POTION
	const EVENT_ROUTE_31_POTION
	const EVENT_ROUTE_31_POKE_BALL
	const EVENT_ROUTE_32_GREAT_BALL
	const EVENT_ROUTE_32_REPEL
	const EVENT_ROUTE_35_TM_ROLLOUT
	const EVENT_ROUTE_42_ULTRA_BALL
	const EVENT_ROUTE_42_SUPER_POTION
	const EVENT_ROUTE_43_MAX_ETHER
	const EVENT_ROUTE_44_MAX_REVIVE
	const EVENT_ROUTE_44_ULTRA_BALL
	const EVENT_ROUTE_45_NUGGET
	const EVENT_ROUTE_45_REVIVE
	const EVENT_ROUTE_45_ELIXER
	const EVENT_ROUTE_45_MAX_POTION
	const EVENT_ROUTE_46_X_SPEED
; Johto people
	const EVENT_RIVAL_NEW_BARK_TOWN
	const EVENT_RIVAL_CHERRYGROVE_CITY
	const EVENT_RIVAL_AZALEA_TOWN
	const EVENT_RIVAL_TEAM_ROCKET_BASE
	const EVENT_RIVAL_GOLDENROD_UNDERGROUND
	const EVENT_RIVAL_VICTORY_ROAD
	const EVENT_RIVAL_OLIVINE_CITY
	const EVENT_RIVAL_SPROUT_TOWER
	const EVENT_RIVAL_BURNED_TOWER
	const EVENT_RIVAL_DRAGONS_DEN
	const EVENT_PLAYERS_HOUSE_KYLE_1
	const EVENT_PLAYERS_HOUSE_KYLE_2
	const EVENT_MR_POKEMONS_HOUSE_OAK
	const EVENT_VIOLET_CITY_EARL
	const EVENT_EARLS_ACADEMY_EARL
	const EVENT_GOLDENROD_CITY_ROCKET_SCOUT
	const EVENT_GOLDENROD_CITY_ROCKET_TAKEOVER
	const EVENT_RADIO_TOWER_ROCKET_TAKEOVER
	const EVENT_GOLDENROD_CITY_CIVILIANS
	const EVENT_RADIO_TOWER_CIVILIANS_AFTER
	const EVENT_RADIO_TOWER_BLACKBELT_BLOCKS_STAIRS
	const EVENT_OLIVINE_LIGHTHOUSE_JASMINE
	const EVENT_OLIVINE_GYM_JASMINE
	const EVENT_LAKE_OF_RAGE_LANCE
	const EVENT_MAHOGANY_MART_LANCE_AND_DRAGONITE
	const EVENT_TEAM_ROCKET_BASE_B2F_LANCE
	const EVENT_TEAM_ROCKET_BASE_B3F_LANCE_PASSWORDS
	const EVENT_DRAGONS_DEN_CLAIR
	const EVENT_TEAM_ROCKET_BASE_SECURITY_GRUNTS
	const EVENT_TEAM_ROCKET_BASE_POPULATION
	const EVENT_TEAM_ROCKET_BASE_B3F_EXECUTIVE
	const EVENT_ROUTE_43_GATE_ROCKETS
	const EVENT_TEAM_ROCKET_BASE_B2F_EXECUTIVE
	const EVENT_TEAM_ROCKET_BASE_B2F_GRUNT_WITH_EXECUTIVE
	const EVENT_TEAM_ROCKET_BASE_B2F_DRAGONITE
	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_1
	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_2
	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_3
	const EVENT_BLACKTHORN_CITY_SUPER_NERD_BLOCKS_GYM
	const EVENT_BLACKTHORN_CITY_SUPER_NERD_DOES_NOT_BLOCK_GYM
	const EVENT_DAY_CARE_MAN_IN_DAY_CARE
	const EVENT_DAY_CARE_MAN_ON_ROUTE_34
	const EVENT_DAY_CARE_MON_1
	const EVENT_DAY_CARE_MON_2
	const EVENT_ILEX_FOREST_FARFETCHD
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_TEACHER_BEHIND_COUNTER
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_LASS
	const EVENT_ROUTE_34_ILEX_FOREST_GATE_TEACHER_IN_WALKWAY
	const EVENT_ILEX_FOREST_LASS
	const EVENT_COPYCAT_1
	const EVENT_COPYCAT_2
	const EVENT_GOLDENROD_SALE_OFF
	const EVENT_GOLDENROD_SALE_ON
	const EVENT_ILEX_FOREST_APPRENTICE
	const EVENT_ILEX_FOREST_CHARCOAL_MASTER
	const EVENT_CHARCOAL_KILN_FARFETCH_D
	const EVENT_CHARCOAL_KILN_APPRENTICE
	const EVENT_CHARCOAL_KILN_BOSS
	const EVENT_ROUTE_36_SUDOWOODO
	const EVENT_AZALEA_TOWN_SLOWPOKES
	const EVENT_AZALEA_TOWN_SLOWPOKETAIL_ROCKET
	const EVENT_SLOWPOKE_WELL_SLOWPOKES
	const EVENT_SLOWPOKE_WELL_ROCKETS
	const EVENT_KURTS_HOUSE_SLOWPOKE
	const EVENT_GUIDE_GENT_IN_HIS_HOUSE
	const EVENT_GUIDE_GENT_VISIBLE_IN_CHERRYGROVE
	const EVENT_ELMS_AIDE_IN_VIOLET_POKEMON_CENTER
	const EVENT_ELMS_AIDE_IN_LAB
	const EVENT_COP_IN_ELMS_LAB
	const EVENT_RUINS_OF_ALPH_OUTSIDE_SCIENTIST
	const EVENT_RUINS_OF_ALPH_RESEARCH_CENTER_SCIENTIST
	const EVENT_RUINS_OF_ALPH_INNER_CHAMBER_TOURISTS
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_1
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_2
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_3
	const EVENT_BOULDER_IN_ICE_PATH_1
	const EVENT_BOULDER_IN_ICE_PATH_2
	const EVENT_BOULDER_IN_ICE_PATH_3
	const EVENT_BOULDER_IN_ICE_PATH_4
	const EVENT_BOULDER_IN_ICE_PATH_1A
	const EVENT_BOULDER_IN_ICE_PATH_2A
	const EVENT_BOULDER_IN_ICE_PATH_3A
	const EVENT_BOULDER_IN_ICE_PATH_4A
	const EVENT_MYSTERY_GIFT_DELIVERY_GUY
	const EVENT_MET_BILL
	const EVENT_ECRUTEAK_POKE_CENTER_BILL
	const EVENT_ROUTE_30_BATTLE
	const EVENT_ROUTE_30_YOUNGSTER_JOEY
	const EVENT_BUG_CATCHING_CONTESTANT_1A
	const EVENT_BUG_CATCHING_CONTESTANT_2A
	const EVENT_BUG_CATCHING_CONTESTANT_3A
	const EVENT_BUG_CATCHING_CONTESTANT_4A
	const EVENT_BUG_CATCHING_CONTESTANT_5A
	const EVENT_BUG_CATCHING_CONTESTANT_6A
	const EVENT_BUG_CATCHING_CONTESTANT_7A
	const EVENT_BUG_CATCHING_CONTESTANT_8A
	const EVENT_BUG_CATCHING_CONTESTANT_9A
	const EVENT_BUG_CATCHING_CONTESTANT_10A
	const EVENT_BUG_CATCHING_CONTESTANT_1B
	const EVENT_BUG_CATCHING_CONTESTANT_2B
	const EVENT_BUG_CATCHING_CONTESTANT_3B
	const EVENT_BUG_CATCHING_CONTESTANT_4B
	const EVENT_BUG_CATCHING_CONTESTANT_5B
	const EVENT_BUG_CATCHING_CONTESTANT_6B
	const EVENT_BUG_CATCHING_CONTESTANT_7B
	const EVENT_BUG_CATCHING_CONTESTANT_8B
	const EVENT_BUG_CATCHING_CONTESTANT_9B
	const EVENT_BUG_CATCHING_CONTESTANT_10B
	const EVENT_OLIVINE_PORT_SAILOR_AT_GANGWAY
	const EVENT_VERMILION_PORT_SAILOR_AT_GANGWAY
	const EVENT_FAST_SHIP_1F_GENTLEMAN
	const EVENT_FAST_SHIP_CABINS_NNW_NNE_NE_SAILOR
	const EVENT_FAST_SHIP_B1F_SAILOR_LEFT
	const EVENT_FAST_SHIP_B1F_SAILOR_RIGHT
	const EVENT_FAST_SHIP_CABINS_SE_SSE_GENTLEMAN
	const EVENT_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_TWIN_1
	const EVENT_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_TWIN_2
	const EVENT_OLIVINE_PORT_PASSAGE_POKEFAN_M
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_YOUNGSTER
	const EVENT_LAKE_OF_RAGE_CIVILIANS
	const EVENT_MAHOGANY_MART_OWNERS
	const EVENT_OLIVINE_PORT_SPRITES_BEFORE_HALL_OF_FAME
	const EVENT_OLIVINE_PORT_SPRITES_AFTER_HALL_OF_FAME
	const EVENT_FAST_SHIP_PASSENGERS_FIRST_TRIP
	const EVENT_FAST_SHIP_PASSENGERS_EASTBOUND
	const EVENT_FAST_SHIP_PASSENGERS_WESTBOUND
	const EVENT_TIN_TOWER_ROOF_HO_OH
	const EVENT_WHIRL_ISLAND_LUGIA_CHAMBER_LUGIA
	const EVENT_KURTS_HOUSE_KURT_1
	const EVENT_KURTS_HOUSE_KURT_2
	const EVENT_SLOWPOKE_WELL_KURT
	const EVENT_PLAYERS_HOUSE_2F_CONSOLE
	const EVENT_PLAYERS_HOUSE_2F_DOLL_1
	const EVENT_PLAYERS_HOUSE_2F_DOLL_2
	const EVENT_PLAYERS_HOUSE_2F_BIG_DOLL
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_35_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_ROUTE_36_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_36_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_GOLDENROD_TRAIN_STATION_GENTLEMAN
	const EVENT_BURNED_TOWER_B1F_BEASTS_1
	const EVENT_BURNED_TOWER_B1F_BEASTS_2
	const EVENT_BLACKTHORN_CITY_GRAMPS_BLOCKS_DRAGONS_DEN
	const EVENT_BLACKTHORN_CITY_GRAMPS_NOT_BLOCKING_DRAGONS_DEN
	const EVENT_RUINS_OF_ALPH_KABUTO_CHAMBER_RECEPTIONIST
	const EVENT_OPENED_MT_SILVER
	const EVENT_FOUGHT_SNORLAX
	const EVENT_LAKE_OF_RAGE_RED_GYARADOS
	const EVENT_GOLDENROD_UNDERGROUND_GRANNY
	const EVENT_GOLDENROD_UNDERGROUND_GRAMPS
	const EVENT_GOLDENROD_UNDERGROUND_OLDER_HAIRCUT_BROTHER
	const EVENT_GOLDENROD_UNDERGROUND_YOUNGER_HAIRCUT_BROTHER
	const EVENT_MAHOGANY_TOWN_POKEFAN_M_BLOCKS_EAST
	const EVENT_MAHOGANY_TOWN_POKEFAN_M_BLOCKS_GYM
	const EVENT_ROUTE_32_FRIEDA_OF_FRIDAY
	const EVENT_ROUTE_29_TUSCANY_OF_TUESDAY
	const EVENT_ROUTE_36_ARTHUR_OF_THURSDAY
	const EVENT_ROUTE_37_SUNNY_OF_SUNDAY
	const EVENT_LAKE_OF_RAGE_WESLEY_OF_WEDNESDAY
	const EVENT_BLACKTHORN_CITY_SANTOS_OF_SATURDAY
	const EVENT_ROUTE_40_MONICA_OF_MONDAY
	const EVENT_LANCES_ROOM_OAK_AND_MARY
	const EVENT_UNION_CAVE_B2F_LAPRAS
	const EVENT_TEAM_ROCKET_DISBANDED
	const EVENT_RED_IN_MT_SILVER
	const EVENT_GOLDENROD_DEPT_STORE_5F_HAPPINESS_EVENT_LADY
	const EVENT_BURNED_TOWER_MORTY
	const EVENT_BURNED_TOWER_1F_EUSINE
	const EVENT_RANG_CLEAR_BELL_1
	const EVENT_RANG_CLEAR_BELL_2
	const EVENT_FLORIA_AT_FLOWER_SHOP
	const EVENT_FLORIA_AT_SUDOWOODO
	const EVENT_GOLDENROD_CITY_MOVE_TUTOR
	const EVENT_GOLDENROD_GAME_CORNER_MOVE_TUTOR
; Unused: next 0 events
; (In pokegold the previous 4 event flags were not defined,
; but in pokecrystal the 'const_next 1900' is redundant.)

; Kanto people
	const EVENT_ROUTE_24_ROCKET
	const EVENT_CERULEAN_GYM_ROCKET
	const EVENT_ROUTE_25_MISTY_BOYFRIEND
	const EVENT_TRAINERS_IN_CERULEAN_GYM
	const EVENT_VERMILION_CITY_SNORLAX
	const EVENT_ROUTE_5_6_POKEFAN_M_BLOCKS_UNDERGROUND_PATH
	const EVENT_SAFFRON_TRAIN_STATION_POPULATION
	const EVENT_COPYCATS_HOUSE_2F_DOLL
	const EVENT_VERMILION_FAN_CLUB_DOLL
	const EVENT_BLUE_IN_CINNABAR
	const EVENT_VIRIDIAN_GYM_BLUE
	const EVENT_SEAFOAM_GYM_GYM_GUIDE
	const EVENT_MT_MOON_SQUARE_ROCK
	const EVENT_MT_MOON_SQUARE_CLEFAIRY
	const EVENT_MT_MOON_RIVAL
	const EVENT_INDIGO_PLATEAU_POKECENTER_RIVAL
	const EVENT_TELEPORT_GUY
; Kanto itemballs
	const EVENT_MAYBE_VILLAGE_FOCUS_BAND
	const EVENT_MISPLACED_WOODS_ELIXER
	const EVENT_MISPLACED_WOODS_IRON
	const EVENT_MISPLACED_WOODS_PP_UP
	const EVENT_MISPLACED_WOODS_REVIVE
	const EVENT_ROCK_TUNNEL_1F_TM_STEEL_WING
	const EVENT_MISPLACED_CAVERN_2F_DIRE_HIT
	const EVENT_MISPLACED_CAVERN_2F_MAX_POTION
	const EVENT_MAYBE_VILLAGE_WELL_PP_UP
	const EVENT_AWAKENING_DUNGEON_ELIXER
	const EVENT_AWAKENING_DUNGEON_HP_UP
	const EVENT_AWAKENING_DUNGEON_CALCIUM
	const EVENT_AWAKENING_DUNGEON_NUGGET
	const EVENT_AWAKENING_DUNGEON_PP_UP
	const EVENT_AWAKENING_DUNGEON_PROTEIN
	const EVENT_AWAKENING_DUNGEON_MAX_REVIVE
	const EVENT_AWAKENING_DUNGEON_B1F_MAX_ETHER
	const EVENT_AWAKENING_DUNGEON_B1F_PP_UP
	const EVENT_AWAKENING_DUNGEON_B1F_MAX_ELIXER
; New to Crystal
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_2
	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_FISHER
	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_YOUNGSTERS
	const EVENT_DRAGON_SHRINE_CLAIR
	const EVENT_BATTLE_TOWER_BATTLE_ROOM_YOUNGSTER
	const EVENT_PLAYERS_HOUSE_1F_NEIGHBOR
	const EVENT_PLAYERS_NEIGHBORS_HOUSE_NEIGHBOR
	const EVENT_PICKED_UP_GOLD_BERRY_FROM_HO_OH_ITEM_ROOM
	const EVENT_PICKED_UP_MYSTERYBERRY_FROM_HO_OH_ITEM_ROOM
	const EVENT_PICKED_UP_REVIVAL_HERB_FROM_HO_OH_ITEM_ROOM
	const EVENT_PICKED_UP_CHARCOAL_FROM_HO_OH_ITEM_ROOM
	const EVENT_PICKED_UP_BERRY_FROM_KABUTO_ITEM_ROOM
	const EVENT_PICKED_UP_PSNCUREBERRY_FROM_KABUTO_ITEM_ROOM
	const EVENT_PICKED_UP_HEAL_POWDER_FROM_KABUTO_ITEM_ROOM
	const EVENT_PICKED_UP_ENERGYPOWDER_FROM_KABUTO_ITEM_ROOM
	const EVENT_PICKED_UP_MYSTERYBERRY_FROM_OMANYTE_ITEM_ROOM
	const EVENT_PICKED_UP_MYSTIC_WATER_FROM_OMANYTE_ITEM_ROOM
	const EVENT_PICKED_UP_STARDUST_FROM_OMANYTE_ITEM_ROOM
	const EVENT_PICKED_UP_STAR_PIECE_FROM_OMANYTE_ITEM_ROOM
	const EVENT_PICKED_UP_GOLD_BERRY_FROM_AERODACTYL_ITEM_ROOM
	const EVENT_PICKED_UP_MOON_STONE_FROM_AERODACTYL_ITEM_ROOM
	const EVENT_PICKED_UP_HEAL_POWDER_FROM_AERODACTYL_ITEM_ROOM
	const EVENT_PICKED_UP_ENERGY_ROOT_FROM_AERODACTYL_ITEM_ROOM
	const EVENT_AZALEA_TOWN_KURT
	const EVENT_ILEX_FOREST_KURT
	const EVENT_MOUNT_MORTAR_1F_INSIDE_MAX_POTION
	const EVENT_MOUNT_MORTAR_1F_INSIDE_NUGGET
	const EVENT_ECRUTEAK_GYM_GRAMPS
	const EVENT_ECRUTEAK_CITY_GRAMPS
	const EVENT_EUSINE_IN_BURNED_TOWER
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_1
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_2
	const EVENT_CIANWOOD_CITY_EUSINE
	const EVENT_SAW_SUICUNE_AT_CIANWOOD_CITY
	const EVENT_SAW_SUICUNE_ON_ROUTE_42
	const EVENT_SAW_SUICUNE_ON_ROUTE_36
	const EVENT_ECRUTEAK_TIN_TOWER_ENTRANCE_WANDERING_SAGE
	const EVENT_TIN_TOWER_1F_SUICUNE
	const EVENT_TIN_TOWER_1F_ENTEI
	const EVENT_TIN_TOWER_1F_RAIKOU
	const EVENT_TIN_TOWER_1F_EUSINE
	const EVENT_TIN_TOWER_1F_WISE_TRIO_1
	const EVENT_SET_WHEN_FOUGHT_HO_OH
	const EVENT_ROUTE_30_ANTIDOTE
	const EVENT_ILEX_FOREST_X_ATTACK
	const EVENT_ILEX_FOREST_ANTIDOTE
	const EVENT_ILEX_FOREST_ETHER
	const EVENT_ROUTE_34_NUGGET
	const EVENT_ROUTE_44_MAX_REPEL
	const EVENT_ICE_PATH_1F_PROTEIN
	const EVENT_DRAGONS_DEN_B1F_CALCIUM
	const EVENT_SILVER_CAVE_ROOM_1_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_CALCIUM
	const EVENT_SILVER_CAVE_ROOM_2_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_PP_UP
	const EVENT_TIN_TOWER_1F_WISE_TRIO_2
	const EVENT_TIN_TOWER_6F_MAX_POTION
	const EVENT_TIN_TOWER_9F_HP_UP
	const EVENT_MOUNT_MORTAR_1F_INSIDE_IRON
	const EVENT_MOUNT_MORTAR_1F_INSIDE_ULTRA_BALL
	const EVENT_MOUNT_MORTAR_B1F_FULL_RESTORE
	const EVENT_RADIO_TOWER_5F_ULTRA_BALL
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_DIRE_HIT
	const EVENT_BATTLE_TOWER_OPEN_CIVILIANS
; Unused: next 48 events

	const_next 2048
DEF NUM_EVENTS EQU const_value ; 800
