; mart types (see engine/items/mart.asm)
	const_def
	const MARTTYPE_STANDARD
	const MARTTYPE_BITTER
	const MARTTYPE_BARGAIN
	const MARTTYPE_PHARMACY
	const MARTTYPE_ROOFTOP
	const MARTTYPE_LOCAL
	const MARTTYPE_SHADY
; Marts indexes (see data/items/marts.asm)
	const_def
	const MART_GEARCITY
	const MART_ROUTE_B_GATE
	const MART_UNIVERCITY_BALLS
	const MART_UNIVERCITY_BATTLE
	const MART_UNIVERCITY_HEALING
	const MART_UNIVERCITY_PP
	const MART_UNIVERCITY_HELD1
	const MART_UNIVERCITY_HELD2
	const MART_UNIVERCITY_TM1
	const MART_UNIVERCITY_TM2
	const MART_UNIVERCITY_TM3
	const MART_UNIVERCITY_EVOLUTION
	const MART_UNIVERCITY_STATS
	const MART_UNIVERCITY_OVERWORLD
	const MART_UNIVERCITY_LOCAL
	const MART_RANCH_1
	const MART_RANCH_2
	const MART_SHADY_GUY_BROCANO
	const MART_MAYBE_VILLAGE
	const MART_THE_BETWEENS
	const MART_GENDER_CLINIC
	const MART_DR_NUGGZ
	const MART_CELADON_3F
	const MART_CELADON_4F
	const MART_CELADON_5F_1
	const MART_CELADON_5F_2
	const MART_FUCHSIA
	const MART_SAFFRON
	const MART_MT_MOON
	const MART_INDIGO_PLATEAU
	const MART_UNDERGROUND
DEF NUM_MARTS EQU const_value
