
	db "Lightning@" ; species name
	dw 207, 540 ; height, weight

	db   "The negatively"
    next "charged ions"
    next "generated by its"

    page "fur create a"
    next "constant sparking"
    next "noise.@"
