	tilepal 0, GRAY, GRAY, WATER, WATER, GRAY, GRAY, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, GRAY, WATER, WATER, GRAY, GRAY, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, RED, RED, RED, RED, WATER, GRAY, GRAY
	tilepal 0, WATER, WATER, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, RED, RED, RED, RED, WATER, GRAY, WATER
	tilepal 0, GRAY, GRAY, BROWN, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, BROWN, RED, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, WATER, WATER, WATER, RED, RED, RED, RED, WATER
	tilepal 0, BROWN, YELLOW, RED, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, WATER, RED, RED, RED, RED, GRAY, RED, WATER
	tilepal 0, RED, BROWN, GREEN, YELLOW, GRAY, ROOF, ROOF, ROOF
	tilepal 0, WATER, WATER, WATER, BROWN, WATER, WATER, RED, RED
	tilepal 0, TEXT, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, GRAY, GRAY, GRAY, GREEN, YELLOW, RED, RED
	tilepal 1, GRAY, GREEN, GREEN, TEXT
