	tilepal 0, GRAY, GRAY, WATER, WATER, RED, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, WATER, GRAY, WATER, WATER, RED, BROWN, BROWN, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, BROWN, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, RED, RED, GRAY, GRAY, GREEN, GREEN, GRAY, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY
	tilepal 0, RED, RED, RED, RED, RED, RED, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, RED, RED, RED, RED
