	tilepal 0, GRAY, BROWN, BROWN, BROWN, RED, GRAY, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, BROWN, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, RED, GRAY, GRAY, WATER, WATER, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, GREEN, ROOF
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, BROWN, BROWN, GRAY, GREEN, GREEN, TEXT
	tilepal 1, RED, WATER, GRAY, TEXT
