AnimationPointers:
	table_width 2, AnimationPointers
	dw SpirripAnimation
	dw DoomstoneAnimation
	dw CryptiidAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw RookideeAnimation
	dw CorvisquireAnimation
	dw CorviknightAnimation
	dw FarfetchdAnimation
	dw LuxwanAnimation
	dw SirfetchdAnimation
	dw YungoosAnimation
	dw GumshoosAnimation
	dw WoolooAnimation
	dw DubwoolAnimation
	dw YamperAnimation
	dw BoltundAnimation
	dw EmolgaAnimation
	dw GrubbinAnimation
	dw CharjabugAnimation
	dw VikavoltAnimation
	dw BlipbugAnimation
	dw DottlerAnimation
	dw OrbeetleAnimation
	dw SizzlipedeAnimation
	dw CentiskorchAnimation
	dw SnomAnimation
	dw FrosmothAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw NoibatAnimation
	dw NoivernAnimation
	dw WoobatAnimation
	dw SwoobatAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw GalladeAnimation
	dw HatennaAnimation
	dw HattremAnimation
	dw HattereneAnimation
	dw ZigzagoonAnimation
	dw LinooneAnimation
	dw ObstagoonAnimation
	dw MudbrayAnimation
	dw MudsdaleAnimation
	dw DeerlingAnimation
	dw SawsbuckAnimation
	dw RockruffAnimation
	dw Lycanroc_middayAnimation
	dw Lycanroc_duskAnimation
	dw Lycanroc_midnightAnimation
	dw BarboachAnimation
	dw WhiscashAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw Mega_gengarAnimation
	dw UnownAnimation
	dw DwebbleAnimation
	dw CrustleAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw MorelullAnimation
	dw ShiinoticAnimation
	dw AlomomolaAnimation
	dw SphealAnimation
	dw SealeoAnimation
	dw WalreinAnimation
	dw DewpiderAnimation
	dw AraquanidAnimation
	dw MareanieAnimation
	dw ToxapexAnimation
	dw BeldumAnimation
	dw MetangAnimation
	dw MetagrossAnimation
	dw LarvestaAnimation
	dw VolcaronaAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw MunnaAnimation
	dw MusharnaAnimation
	dw SolosisAnimation
	dw DuosionAnimation
	dw ReuniclusAnimation
	dw DittoAnimation
	dw TrubbishAnimation
	dw GarbodorAnimation
	dw SalanditAnimation
	dw SalazzleAnimation
	dw StunkyAnimation
	dw SkuntankAnimation
	dw GrenmarAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw CherubiAnimation
	dw CherrimAnimation
	dw BounsweetAnimation
	dw SteeneeAnimation
	dw TsareenaAnimation
	dw BouffalantAnimation
	dw FomantisAnimation
	dw LurantisAnimation
	dw ScytherAnimation
	dw ScizorAnimation
	dw KleavorAnimation
	dw HeracrossAnimation
	dw CombeeAnimation
	dw VespiquenAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw EspurrAnimation
	dw Meowstic_mAnimation
	dw Meowstic_fAnimation
	dw PurrloinAnimation
	dw LiepardAnimation
	dw SkittyAnimation
	dw DelcattyAnimation
	dw LitleoAnimation
	dw PyroarAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw StantlerAnimation
	dw WyrdeerAnimation
	dw ChatotAnimation
	dw DrilburAnimation
	dw ExcadrillAnimation
	dw MakuhitaAnimation
	dw HariyamaAnimation
	dw MeowthAnimation
	dw PerrserkerAnimation
	dw ChompAnimation
	dw RegimagmaAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw ClobbopusAnimation
	dw GrapploctAnimation
	dw Jangmo_oAnimation
	dw Hakamo_oAnimation
	dw Kommo_oAnimation
	dw LillipupAnimation
	dw HerdierAnimation
	dw StoutlandAnimation
	dw Salandit2Animation
	dw Salazzle2Animation
	dw TykerAnimation
	dw StraigarAnimation
	dw TympoleAnimation
	dw PalpitoadAnimation
	dw SeismitoadAnimation
	dw PikipekAnimation
	dw TrumbeakAnimation
	dw ToucannonAnimation
	dw HeatmorAnimation
	dw MolambinoAnimation
	dw AngoreAnimation
	dw ClauncherAnimation
	dw ClawitzerAnimation
	dw BuizelAnimation
	dw FloatzelAnimation
	dw ShellosAnimation
	dw GastrodonAnimation
	dw FinneonAnimation
	dw LumineonAnimation
	dw TirtougaAnimation
	dw CarracostaAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw BurgelaAnimation
	dw TangelaAnimation
	dw TangrowthAnimation
	dw JungelaAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw GlaceonAnimation
	dw LeafeonAnimation
	dw SylveonAnimation
	dw BuzzeonAnimation
	dw DurantAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw UrsalunaAnimation
	dw SnoverAnimation
	dw AbomasnowAnimation
	dw SkarmoryAnimation
	dw BlitzleAnimation
	dw ZebstrikaAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SandygastAnimation
	dw PalossandAnimation
	dw StuffulAnimation
	dw BewearAnimation
	dw Oricorio_baileAnimation
	dw Oricorio_pomAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw Oricorio_pauAnimation
	dw Oricorio_sensuAnimation
	dw OranguruAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw PorygonAnimation
	dw Porygon2Animation
	dw Porygon_zAnimation
	dw LaprasAnimation
	dw AmauraAnimation
	dw AurorusAnimation
	dw Minior_meteorAnimation
	dw Minior_coreAnimation
	dw DrampaAnimation
	dw SnorlaxAnimation
	dw MawileAnimation
	dw Mega_mawileAnimation
	dw SkrelpAnimation
	dw DragalgeAnimation
	dw DreepyAnimation
	dw DrakloakAnimation
	dw DragapultAnimation
	dw BruxishAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw SuicuneAnimation
	dw ApplinAnimation
	dw FlappleAnimation
	dw AppletunAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw ZacianAnimation
	dw MewthreeAnimation
	dw PoppyAnimation
	dw DaisyAnimation
	dw BoomerAnimation
	dw KirbyAnimation
	dw M_blockAnimation
	dw Bad_eggAnimation
	dw FuriousbAnimation
    assert_table_length NUM_POKEMON
