BitmasksPointers:
	table_width 2, BitmasksPointers
	dw SpirripBitmasks
	dw DoomstoneBitmasks
	dw CryptiidBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw HonedgeBitmasks
	dw DoubladeBitmasks
	dw AegislashBitmasks
	dw RookideeBitmasks
	dw CorvisquireBitmasks
	dw CorviknightBitmasks
	dw FarfetchdBitmasks
	dw LuxwanBitmasks
	dw SirfetchdBitmasks
	dw YungoosBitmasks
	dw GumshoosBitmasks
	dw WoolooBitmasks
	dw DubwoolBitmasks
	dw YamperBitmasks
	dw BoltundBitmasks
	dw EmolgaBitmasks
	dw GrubbinBitmasks
	dw CharjabugBitmasks
	dw VikavoltBitmasks
	dw BlipbugBitmasks
	dw DottlerBitmasks
	dw OrbeetleBitmasks
	dw SizzlipedeBitmasks
	dw CentiskorchBitmasks
	dw SnomBitmasks
	dw FrosmothBitmasks
	dw AronBitmasks
	dw LaironBitmasks
	dw AggronBitmasks
	dw NoibatBitmasks
	dw NoivernBitmasks
	dw WoobatBitmasks
	dw SwoobatBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GalladeBitmasks
	dw HatennaBitmasks
	dw HattremBitmasks
	dw HattereneBitmasks
	dw ZigzagoonBitmasks
	dw LinooneBitmasks
	dw ObstagoonBitmasks
	dw MudbrayBitmasks
	dw MudsdaleBitmasks
	dw DeerlingBitmasks
	dw SawsbuckBitmasks
	dw RockruffBitmasks
	dw Lycanroc_middayBitmasks
	dw Lycanroc_duskBitmasks
	dw Lycanroc_midnightBitmasks
	dw BarboachBitmasks
	dw WhiscashBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw Mega_gengarBitmasks
	dw UnownBitmasks
	dw DwebbleBitmasks
	dw CrustleBitmasks
	dw LotadBitmasks
	dw LombreBitmasks
	dw LudicoloBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw MorelullBitmasks
	dw ShiinoticBitmasks
	dw AlomomolaBitmasks
	dw SphealBitmasks
	dw SealeoBitmasks
	dw WalreinBitmasks
	dw DewpiderBitmasks
	dw AraquanidBitmasks
	dw MareanieBitmasks
	dw ToxapexBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw JoltikBitmasks
	dw GalvantulaBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw MunnaBitmasks
	dw MusharnaBitmasks
	dw SolosisBitmasks
	dw DuosionBitmasks
	dw ReuniclusBitmasks
	dw DittoBitmasks
	dw TrubbishBitmasks
	dw GarbodorBitmasks
	dw SalanditBitmasks
	dw SalazzleBitmasks
	dw StunkyBitmasks
	dw SkuntankBitmasks
	dw GrenmarBitmasks
	dw YanmaBitmasks
	dw YanmegaBitmasks
	dw CherubiBitmasks
	dw CherrimBitmasks
	dw BounsweetBitmasks
	dw SteeneeBitmasks
	dw TsareenaBitmasks
	dw BouffalantBitmasks
	dw FomantisBitmasks
	dw LurantisBitmasks
	dw ScytherBitmasks
	dw ScizorBitmasks
	dw KleavorBitmasks
	dw HeracrossBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw EspurrBitmasks
	dw Meowstic_mBitmasks
	dw Meowstic_fBitmasks
	dw PurrloinBitmasks
	dw LiepardBitmasks
	dw SkittyBitmasks
	dw DelcattyBitmasks
	dw LitleoBitmasks
	dw PyroarBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw StantlerBitmasks
	dw WyrdeerBitmasks
	dw ChatotBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw MakuhitaBitmasks
	dw HariyamaBitmasks
	dw MeowthBitmasks
	dw PerrserkerBitmasks
	dw WingullBitmasks
	dw PelipperBitmasks
	dw CroagunkBitmasks
	dw ToxicroakBitmasks
	dw ClobbopusBitmasks
	dw GrapploctBitmasks
	dw Jangmo_oBitmasks
	dw Hakamo_oBitmasks
	dw Kommo_oBitmasks
	dw LillipupBitmasks
	dw HerdierBitmasks
	dw StoutlandBitmasks
	dw Salandit2Bitmasks
	dw Salazzle2Bitmasks
	dw TykerBitmasks
	dw StraigarBitmasks
	dw TympoleBitmasks
	dw PalpitoadBitmasks
	dw SeismitoadBitmasks
	dw PikipekBitmasks
	dw TrumbeakBitmasks
	dw ToucannonBitmasks
	dw HeatmorBitmasks
	dw MolambinoBitmasks
	dw AngoreBitmasks
	dw ClauncherBitmasks
	dw ClawitzerBitmasks
	dw BuizelBitmasks
	dw FloatzelBitmasks
	dw ShellosBitmasks
	dw GastrodonBitmasks
	dw FinneonBitmasks
	dw LumineonBitmasks
	dw TirtougaBitmasks
	dw CarracostaBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw BurgelaBitmasks
	dw TangelaBitmasks
	dw TangrowthBitmasks
	dw JungelaBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw GlaceonBitmasks
	dw LeafeonBitmasks
	dw SylveonBitmasks
	dw DurantBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw MamoswineBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw UrsalunaBitmasks
	dw SnoverBitmasks
	dw AbomasnowBitmasks
	dw SkarmoryBitmasks
	dw BlitzleBitmasks
	dw ZebstrikaBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SandygastBitmasks
	dw PalossandBitmasks
	dw StuffulBitmasks
	dw BewearBitmasks
	dw Oricorio_baileBitmasks
	dw Oricorio_pomBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw Oricorio_pauBitmasks
	dw Oricorio_sensuBitmasks
	dw OranguruBitmasks
	dw MisdreavusBitmasks
	dw MismagiusBitmasks
	dw PorygonBitmasks
	dw Porygon2Bitmasks
	dw Porygon_zBitmasks
	dw LaprasBitmasks
	dw AmauraBitmasks
	dw AurorusBitmasks
	dw Minior_meteorBitmasks
	dw Minior_coreBitmasks
	dw DrampaBitmasks
	dw SnorlaxBitmasks
	dw MawileBitmasks
	dw Mega_mawileBitmasks
	dw SkrelpBitmasks
	dw DragalgeBitmasks
	dw DreepyBitmasks
	dw DrakloakBitmasks
	dw DragapultBitmasks
	dw BruxishBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw SuicuneBitmasks
	dw ApplinBitmasks
	dw FlappleBitmasks
	dw AppletunBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw ZacianBitmasks
	dw BuzzwoleBitmasks
	dw PoppyBitmasks
	dw DaisyBitmasks
	dw BoomerBitmasks
	dw KirbyBitmasks
	dw M_blockBitmasks
	dw Bad_eggBitmasks
	dw FuriousbBitmasks
    assert_table_length NUM_POKEMON
