FramesPointers:
	table_width 2, FramesPointers
	dw SpirripFrames
	dw DoomstoneFrames
	dw CryptiidFrames
	dw LitwickFrames
	dw LampentFrames
	dw ChandelureFrames
	dw RookideeFrames
	dw CorvisquireFrames
	dw CorviknightFrames
	dw FarfetchdFrames
	dw LuxwanFrames
	dw SirfetchdFrames
	dw YungoosFrames
	dw GumshoosFrames
	dw WoolooFrames
	dw DubwoolFrames
	dw YamperFrames
	dw BoltundFrames
	dw EmolgaFrames
	dw GrubbinFrames
	dw CharjabugFrames
	dw VikavoltFrames
	dw BlipbugFrames
	dw DottlerFrames
	dw OrbeetleFrames
	dw SizzlipedeFrames
	dw CentiskorchFrames
	dw SnomFrames
	dw FrosmothFrames
	dw AronFrames
	dw LaironFrames
	dw AggronFrames
	dw NoibatFrames
	dw NoivernFrames
	dw WoobatFrames
	dw SwoobatFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw GalladeFrames
	dw HatennaFrames
	dw HattremFrames
	dw HattereneFrames
	dw ZigzagoonFrames
	dw LinooneFrames
	dw ObstagoonFrames
	dw MudbrayFrames
	dw MudsdaleFrames
	dw DeerlingFrames
	dw SawsbuckFrames
	dw RockruffFrames
	dw Lycanroc_middayFrames
	dw Lycanroc_duskFrames
	dw Lycanroc_midnightFrames
	dw BarboachFrames
	dw WhiscashFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw Mega_gengarFrames
	dw UnownFrames
	dw DwebbleFrames
	dw CrustleFrames
	dw LotadFrames
	dw LombreFrames
	dw LudicoloFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw MorelullFrames
	dw ShiinoticFrames
	dw AlomomolaFrames
	dw SphealFrames
	dw SealeoFrames
	dw WalreinFrames
	dw DewpiderFrames
	dw AraquanidFrames
	dw MareanieFrames
	dw ToxapexFrames
	dw BeldumFrames
	dw MetangFrames
	dw MetagrossFrames
	dw LarvestaFrames
	dw VolcaronaFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw MunnaFrames
	dw MusharnaFrames
	dw SolosisFrames
	dw DuosionFrames
	dw ReuniclusFrames
	dw DittoFrames
	dw TrubbishFrames
	dw GarbodorFrames
	dw SalanditFrames
	dw SalazzleFrames
	dw StunkyFrames
	dw SkuntankFrames
	dw GrenmarFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw CherubiFrames
	dw CherrimFrames
	dw BounsweetFrames
	dw SteeneeFrames
	dw TsareenaFrames
	dw BouffalantFrames
	dw FomantisFrames
	dw LurantisFrames
	dw ScytherFrames
	dw ScizorFrames
	dw KleavorFrames
	dw HeracrossFrames
	dw CombeeFrames
	dw VespiquenFrames
	dw KoffingFrames
	dw WeezingFrames
	dw GrimerFrames
	dw MukFrames
	dw EspurrFrames
	dw Meowstic_mFrames
	dw Meowstic_fFrames
	dw PurrloinFrames
	dw LiepardFrames
	dw SkittyFrames
	dw DelcattyFrames
	dw LitleoFrames
	dw PyroarFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw StantlerFrames
	dw WyrdeerFrames
	dw ChatotFrames
	dw DrilburFrames
	dw ExcadrillFrames
	dw MakuhitaFrames
	dw HariyamaFrames
	dw MeowthFrames
	dw PerrserkerFrames
	dw WingullFrames
	dw PelipperFrames
	dw CroagunkFrames
	dw ToxicroakFrames
	dw ClobbopusFrames
	dw GrapploctFrames
	dw Jangmo_oFrames
	dw Hakamo_oFrames
	dw Kommo_oFrames
	dw LillipupFrames
	dw HerdierFrames
	dw StoutlandFrames
	dw Salandit2Frames
	dw Salazzle2Frames
	dw TykerFrames
	dw StraigarFrames
	dw TympoleFrames
	dw PalpitoadFrames
	dw SeismitoadFrames
	dw PikipekFrames
	dw TrumbeakFrames
	dw ToucannonFrames
	dw HeatmorFrames
	dw MolambinoFrames
	dw AngoreFrames
	dw ClauncherFrames
	dw ClawitzerFrames
	dw BuizelFrames
	dw FloatzelFrames
	dw ShellosFrames
	dw GastrodonFrames
	dw FinneonFrames
	dw LumineonFrames
	dw TirtougaFrames
	dw CarracostaFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw BurgelaFrames
	dw TangelaFrames
	dw TangrowthFrames
	dw JungelaFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw GlaceonFrames
	dw LeafeonFrames
	dw SylveonFrames
	dw BuzzeonFrames
	dw DurantFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw UrsalunaFrames
	dw SnoverFrames
	dw AbomasnowFrames
	dw SkarmoryFrames
	dw BlitzleFrames
	dw ZebstrikaFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SandygastFrames
	dw PalossandFrames
	dw StuffulFrames
	dw BewearFrames
	dw Oricorio_baileFrames
	dw Oricorio_pomFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw Oricorio_pauFrames
	dw Oricorio_sensuFrames
	dw OranguruFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw Porygon_zFrames
	dw LaprasFrames
	dw AmauraFrames
	dw AurorusFrames
	dw Minior_meteorFrames
	dw Minior_coreFrames
	dw DrampaFrames
	dw SnorlaxFrames
	dw MawileFrames
	dw Mega_mawileFrames
	dw SkrelpFrames
	dw DragalgeFrames
	dw DreepyFrames
	dw DrakloakFrames
	dw DragapultFrames
	dw BruxishFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw SuicuneFrames
	dw ApplinFrames
	dw FlappleFrames
	dw AppletunFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw ZacianFrames
	dw BuzzwoleFrames
	dw PoppyFrames
	dw DaisyFrames
	dw BoomerFrames
	dw KirbyFrames
	dw M_blockFrames
	dw Bad_eggFrames
	dw FuriousbFrames
    assert_table_length NUM_POKEMON
