AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw SpirripAnimationIdle
	dw DoomstoneAnimationIdle
	dw CryptiidAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw RookideeAnimationIdle
	dw CorvisquireAnimationIdle
	dw CorviknightAnimationIdle
	dw FarfetchdAnimationIdle
	dw LuxwanAnimationIdle
	dw SirfetchdAnimationIdle
	dw YungoosAnimationIdle
	dw GumshoosAnimationIdle
	dw WoolooAnimationIdle
	dw DubwoolAnimationIdle
	dw YamperAnimationIdle
	dw BoltundAnimationIdle
	dw EmolgaAnimationIdle
	dw GrubbinAnimationIdle
	dw CharjabugAnimationIdle
	dw VikavoltAnimationIdle
	dw BlipbugAnimationIdle
	dw DottlerAnimationIdle
	dw OrbeetleAnimationIdle
	dw SizzlipedeAnimationIdle
	dw CentiskorchAnimationIdle
	dw SnomAnimationIdle
	dw FrosmothAnimationIdle
	dw AronAnimationIdle
	dw LaironAnimationIdle
	dw AggronAnimationIdle
	dw NoibatAnimationIdle
	dw NoivernAnimationIdle
	dw WoobatAnimationIdle
	dw SwoobatAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw GardevoirAnimationIdle
	dw GalladeAnimationIdle
	dw HatennaAnimationIdle
	dw HattremAnimationIdle
	dw HattereneAnimationIdle
	dw ZigzagoonAnimationIdle
	dw LinooneAnimationIdle
	dw ObstagoonAnimationIdle
	dw MudbrayAnimationIdle
	dw MudsdaleAnimationIdle
	dw DeerlingAnimationIdle
	dw SawsbuckAnimationIdle
	dw RockruffAnimationIdle
	dw Lycanroc_middayAnimationIdle
	dw Lycanroc_duskAnimationIdle
	dw Lycanroc_midnightAnimationIdle
	dw BarboachAnimationIdle
	dw WhiscashAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw Mega_gengarAnimationIdle
	dw UnownAnimationIdle
	dw DwebbleAnimationIdle
	dw CrustleAnimationIdle
	dw LotadAnimationIdle
	dw LombreAnimationIdle
	dw LudicoloAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw MorelullAnimationIdle
	dw ShiinoticAnimationIdle
	dw AlomomolaAnimationIdle
	dw SphealAnimationIdle
	dw SealeoAnimationIdle
	dw WalreinAnimationIdle
	dw DewpiderAnimationIdle
	dw AraquanidAnimationIdle
	dw MareanieAnimationIdle
	dw ToxapexAnimationIdle
	dw BeldumAnimationIdle
	dw MetangAnimationIdle
	dw MetagrossAnimationIdle
	dw LarvestaAnimationIdle
	dw VolcaronaAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw MunnaAnimationIdle
	dw MusharnaAnimationIdle
	dw SolosisAnimationIdle
	dw DuosionAnimationIdle
	dw ReuniclusAnimationIdle
	dw DittoAnimationIdle
	dw TrubbishAnimationIdle
	dw GarbodorAnimationIdle
	dw SalanditAnimationIdle
	dw SalazzleAnimationIdle
	dw StunkyAnimationIdle
	dw SkuntankAnimationIdle
	dw GrenmarAnimationIdle
	dw YanmaAnimationIdle
	dw YanmegaAnimationIdle
	dw CherubiAnimationIdle
	dw CherrimAnimationIdle
	dw BounsweetAnimationIdle
	dw SteeneeAnimationIdle
	dw TsareenaAnimationIdle
	dw BouffalantAnimationIdle
	dw FomantisAnimationIdle
	dw LurantisAnimationIdle
	dw ScytherAnimationIdle
	dw ScizorAnimationIdle
	dw KleavorAnimationIdle
	dw HeracrossAnimationIdle
	dw CombeeAnimationIdle
	dw VespiquenAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw EspurrAnimationIdle
	dw Meowstic_mAnimationIdle
	dw Meowstic_fAnimationIdle
	dw PurrloinAnimationIdle
	dw LiepardAnimationIdle
	dw SkittyAnimationIdle
	dw DelcattyAnimationIdle
	dw LitleoAnimationIdle
	dw PyroarAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw StantlerAnimationIdle
	dw WyrdeerAnimationIdle
	dw ChatotAnimationIdle
	dw DrilburAnimationIdle
	dw ExcadrillAnimationIdle
	dw MakuhitaAnimationIdle
	dw HariyamaAnimationIdle
	dw MeowthAnimationIdle
	dw PerrserkerAnimationIdle
	dw WingullAnimationIdle
	dw RegimagmaAnimationIdle
	dw CroagunkAnimationIdle
	dw ToxicroakAnimationIdle
	dw ClobbopusAnimationIdle
	dw GrapploctAnimationIdle
	dw Jangmo_oAnimationIdle
	dw Hakamo_oAnimationIdle
	dw Kommo_oAnimationIdle
	dw LillipupAnimationIdle
	dw HerdierAnimationIdle
	dw StoutlandAnimationIdle
	dw Salandit2AnimationIdle
	dw Salazzle2AnimationIdle
	dw TykerAnimationIdle
	dw StraigarAnimationIdle
	dw TympoleAnimationIdle
	dw PalpitoadAnimationIdle
	dw SeismitoadAnimationIdle
	dw PikipekAnimationIdle
	dw TrumbeakAnimationIdle
	dw ToucannonAnimationIdle
	dw HeatmorAnimationIdle
	dw MolambinoAnimationIdle
	dw AngoreAnimationIdle
	dw ClauncherAnimationIdle
	dw ClawitzerAnimationIdle
	dw BuizelAnimationIdle
	dw FloatzelAnimationIdle
	dw ShellosAnimationIdle
	dw GastrodonAnimationIdle
	dw FinneonAnimationIdle
	dw LumineonAnimationIdle
	dw TirtougaAnimationIdle
	dw CarracostaAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw BurgelaAnimationIdle
	dw TangelaAnimationIdle
	dw TangrowthAnimationIdle
	dw JungelaAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw GlaceonAnimationIdle
	dw LeafeonAnimationIdle
	dw SylveonAnimationIdle
	dw BuzzeonAnimationIdle
	dw DurantAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw MamoswineAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw UrsalunaAnimationIdle
	dw SnoverAnimationIdle
	dw AbomasnowAnimationIdle
	dw SkarmoryAnimationIdle
	dw BlitzleAnimationIdle
	dw ZebstrikaAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SandygastAnimationIdle
	dw PalossandAnimationIdle
	dw StuffulAnimationIdle
	dw BewearAnimationIdle
	dw Oricorio_baileAnimationIdle
	dw Oricorio_pomAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw Oricorio_pauAnimationIdle
	dw Oricorio_sensuAnimationIdle
	dw OranguruAnimationIdle
	dw MisdreavusAnimationIdle
	dw MismagiusAnimationIdle
	dw PorygonAnimationIdle
	dw Porygon2AnimationIdle
	dw Porygon_zAnimationIdle
	dw LaprasAnimationIdle
	dw AmauraAnimationIdle
	dw AurorusAnimationIdle
	dw Minior_meteorAnimationIdle
	dw Minior_coreAnimationIdle
	dw DrampaAnimationIdle
	dw SnorlaxAnimationIdle
	dw MawileAnimationIdle
	dw Mega_mawileAnimationIdle
	dw SkrelpAnimationIdle
	dw DragalgeAnimationIdle
	dw DreepyAnimationIdle
	dw DrakloakAnimationIdle
	dw DragapultAnimationIdle
	dw BruxishAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw SuicuneAnimationIdle
	dw ApplinAnimationIdle
	dw FlappleAnimationIdle
	dw AppletunAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw ZacianAnimationIdle
	dw BuzzwoleAnimationIdle
	dw PoppyAnimationIdle
	dw DaisyAnimationIdle
	dw BoomerAnimationIdle
	dw KirbyAnimationIdle
	dw M_blockAnimationIdle
	dw Bad_eggAnimationIdle
	dw FuriousbAnimationIdle
    assert_table_length NUM_POKEMON
