; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

CaseyPic:           INCBIN "gfx/trainers/casey.2bpp.lz"
JordanPic:          INCBIN "gfx/trainers/jordan.2bpp.lz"
KylePic:            INCBIN "gfx/trainers/kyle.2bpp.lz"
LeePic:             INCBIN "gfx/trainers/lee.2bpp.lz"
MerPic:             INCBIN "gfx/trainers/mer.2bpp.lz"
Rival1Pic:          INCBIN "gfx/trainers/rival_1.2bpp.lz"
Rival2Pic:          INCBIN "gfx/trainers/rival_2.2bpp.lz"
RyanPic:            INCBIN "gfx/trainers/ryan.2bpp.lz"
SanhaPic:           INCBIN "gfx/trainers/sanha.2bpp.lz"
SarahPic:           INCBIN "gfx/trainers/sarah.2bpp.lz"
FurryPic:           INCBIN "gfx/trainers/furry.2bpp.lz"
LoaferPic:          INCBIN "gfx/trainers/loafer.2bpp.lz"
LinkPic:            INCBIN "gfx/trainers/link.2bpp.lz"
SoraPic:            INCBIN "gfx/trainers/sora.2bpp.lz"
GoronPic:           INCBIN "gfx/trainers/goron.2bpp.lz"
ArtistPic:          INCBIN "gfx/trainers/artist.2bpp.lz"
BattleGirlPic:      INCBIN "gfx/trainers/battle_girl.2bpp.lz"
BikerPic:           INCBIN "gfx/trainers/biker.2bpp.lz"
BirdKeeperPic:      INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
BlackbeltTPic:      INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BluePic:            INCBIN "gfx/trainers/blue.2bpp.lz"
BoarderPic:         INCBIN "gfx/trainers/boarder.2bpp.lz"
BugCatcherPic:      INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
BugManiacPic:       INCBIN "gfx/trainers/bug_maniac.2bpp.lz"

SECTION "Pics 2", ROMX

BurglarPic:         INCBIN "gfx/trainers/burglar.2bpp.lz"
CalPic:             INCBIN "gfx/trainers/cal.2bpp.lz"
CamperPic:          INCBIN "gfx/trainers/camper.2bpp.lz"
CeoPic:             INCBIN "gfx/trainers/ceo.2bpp.lz"
ChampionPic:        INCBIN "gfx/trainers/champion.2bpp.lz"
CooltrainerFPic:    INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
CooltrainerMPic:    INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
CouplePic:          INCBIN "gfx/trainers/couple.2bpp.lz"
DetectiveFPic:      INCBIN "gfx/trainers/detective_f.2bpp.lz"
DetectiveMPic:      INCBIN "gfx/trainers/detective_m.2bpp.lz"
EngineerPic:        INCBIN "gfx/trainers/engineer.2bpp.lz"
FancyLadPic:        INCBIN "gfx/trainers/fancy_lad.2bpp.lz"
FedoraManPic:       INCBIN "gfx/trainers/fedora_man.2bpp.lz"
FeralChildPic:      INCBIN "gfx/trainers/feral_child.2bpp.lz"
FirebreatherPic:    INCBIN "gfx/trainers/firebreather.2bpp.lz"
FisherPic:          INCBIN "gfx/trainers/fisher.2bpp.lz"
GhostPic:           INCBIN "gfx/trainers/ghost.2bpp.lz"
GirlBossPic:        INCBIN "gfx/trainers/girl_boss.2bpp.lz"
GlitchPic:          INCBIN "gfx/trainers/glitch.2bpp.lz"
GrampsPic:          INCBIN "gfx/trainers/gramps.2bpp.lz"
GrannyPic:          INCBIN "gfx/trainers/granny.2bpp.lz"
GuitaristPic:       INCBIN "gfx/trainers/guitarist.2bpp.lz"
HexManiacPic:       INCBIN "gfx/trainers/hex_maniac.2bpp.lz"
HikerPic:           INCBIN "gfx/trainers/hiker.2bpp.lz"
TheEmptyPic:        INCBIN "gfx/trainers/the_empty.2bpp.lz"

SECTION "Pics 3", ROMX

ItGuyPic:           INCBIN "gfx/trainers/it_guy.2bpp.lz"
JugglerPic:         INCBIN "gfx/trainers/juggler.2bpp.lz"
KarateKingPic:      INCBIN "gfx/trainers/karate_king.2bpp.lz"
KarenPic:           INCBIN "gfx/trainers/karen.2bpp.lz"
KimonoGirlPic:      INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
LadyPic:            INCBIN "gfx/trainers/lady.2bpp.lz"
LassPic:            INCBIN "gfx/trainers/lass.2bpp.lz"
MadScientistPic:    INCBIN "gfx/trainers/mad_scientist.2bpp.lz"
MediumPic:          INCBIN "gfx/trainers/medium.2bpp.lz"
NinjaFPic:          INCBIN "gfx/trainers/ninja_f.2bpp.lz"
NinjaMPic:          INCBIN "gfx/trainers/ninja_m.2bpp.lz"
OfficerPic:         INCBIN "gfx/trainers/officer.2bpp.lz"
ProfessorPic:       INCBIN "gfx/trainers/professor.2bpp.lz"
PastorPic:          INCBIN "gfx/trainers/pastor.2bpp.lz"
PhotographerPic:    INCBIN "gfx/trainers/photographer.2bpp.lz"
PicnickerPic:       INCBIN "gfx/trainers/picnicker.2bpp.lz"
PsychicTPic:        INCBIN "gfx/trainers/psychic_t.2bpp.lz"
PyroPic:            INCBIN "gfx/trainers/pyro.2bpp.lz"
RedPic:             INCBIN "gfx/trainers/red.2bpp.lz"
RuffianPic:         INCBIN "gfx/trainers/ruffian.2bpp.lz"
RuinManiacPic:      INCBIN "gfx/trainers/ruin_maniac.2bpp.lz"
SafariPic:          INCBIN "gfx/trainers/safari.2bpp.lz"
SagePic:            INCBIN "gfx/trainers/sage.2bpp.lz"
SailorPic:          INCBIN "gfx/trainers/sailor.2bpp.lz"
OctorokPic:         INCBIN "gfx/trainers/octorok.2bpp.lz"
ShopkeeperPic:      INCBIN "gfx/trainers/shopkeeper.2bpp.lz"
MoblinPic:          INCBIN "gfx/trainers/moblin.2bpp.lz"
ArmosPic:           INCBIN "gfx/trainers/armos.2bpp.lz"

SECTION "Pics 4", ROMX
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_A/front.animated.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_B/front.animated.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_C/front.animated.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_D/front.animated.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_E/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_F/front.animated.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_G/front.animated.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_H/front.animated.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_I/front.animated.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_J/front.animated.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_K/front.animated.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_L/front.animated.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_M/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_N/front.animated.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_O/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_P/front.animated.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_Q/front.animated.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_R/front.animated.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_S/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_T/front.animated.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_U/front.animated.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_V/front.animated.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_W/front.animated.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_X/front.animated.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_Y/front.animated.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_Z/front.animated.2bpp.lz"



SECTION "Pics 5", ROMX

UnownABackpic:      INCBIN "gfx/pokemon/unown_A/back.2bpp.lz"
UnownBBackpic:      INCBIN "gfx/pokemon/unown_B/back.2bpp.lz"
UnownCBackpic:      INCBIN "gfx/pokemon/unown_C/back.2bpp.lz"
UnownDBackpic:      INCBIN "gfx/pokemon/unown_D/back.2bpp.lz"
UnownEBackpic:      INCBIN "gfx/pokemon/unown_E/back.2bpp.lz"
UnownFBackpic:      INCBIN "gfx/pokemon/unown_F/back.2bpp.lz"
UnownGBackpic:      INCBIN "gfx/pokemon/unown_G/back.2bpp.lz"
UnownHBackpic:      INCBIN "gfx/pokemon/unown_H/back.2bpp.lz"
UnownIBackpic:      INCBIN "gfx/pokemon/unown_I/back.2bpp.lz"
UnownJBackpic:      INCBIN "gfx/pokemon/unown_J/back.2bpp.lz"
UnownKBackpic:      INCBIN "gfx/pokemon/unown_K/back.2bpp.lz"
UnownLBackpic:      INCBIN "gfx/pokemon/unown_L/back.2bpp.lz"
UnownMBackpic:      INCBIN "gfx/pokemon/unown_M/back.2bpp.lz"
UnownNBackpic:      INCBIN "gfx/pokemon/unown_N/back.2bpp.lz"
UnownOBackpic:      INCBIN "gfx/pokemon/unown_O/back.2bpp.lz"
UnownPBackpic:      INCBIN "gfx/pokemon/unown_P/back.2bpp.lz"
UnownQBackpic:      INCBIN "gfx/pokemon/unown_Q/back.2bpp.lz"
UnownRBackpic:      INCBIN "gfx/pokemon/unown_R/back.2bpp.lz"
UnownSBackpic:      INCBIN "gfx/pokemon/unown_S/back.2bpp.lz"
UnownTBackpic:      INCBIN "gfx/pokemon/unown_T/back.2bpp.lz"
UnownUBackpic:      INCBIN "gfx/pokemon/unown_U/back.2bpp.lz"
UnownVBackpic:      INCBIN "gfx/pokemon/unown_V/back.2bpp.lz"
UnownWBackpic:      INCBIN "gfx/pokemon/unown_W/back.2bpp.lz"
UnownXBackpic:      INCBIN "gfx/pokemon/unown_X/back.2bpp.lz"
UnownYBackpic:      INCBIN "gfx/pokemon/unown_Y/back.2bpp.lz"
UnownZBackpic:      INCBIN "gfx/pokemon/unown_Z/back.2bpp.lz"


SECTION "Pics 6", ROMX
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
AbomasnowFrontpic:      INCBIN "gfx/pokemon/abomasnow/front.animated.2bpp.lz"
AbomasnowBackpic:      INCBIN "gfx/pokemon/abomasnow/back.2bpp.lz"
CombeeFrontpic:      INCBIN "gfx/pokemon/combee/front.animated.2bpp.lz"
CombeeBackpic:      INCBIN "gfx/pokemon/combee/back.2bpp.lz"
AggronFrontpic:      INCBIN "gfx/pokemon/aggron/front.animated.2bpp.lz"
AggronBackpic:      INCBIN "gfx/pokemon/aggron/back.2bpp.lz"
AlomomolaFrontpic:      INCBIN "gfx/pokemon/alomomola/front.animated.2bpp.lz"
AlomomolaBackpic:      INCBIN "gfx/pokemon/alomomola/back.2bpp.lz"
AmauraFrontpic:      INCBIN "gfx/pokemon/amaura/front.animated.2bpp.lz"
AmauraBackpic:      INCBIN "gfx/pokemon/amaura/back.2bpp.lz"
AngoreFrontpic:      INCBIN "gfx/pokemon/angore/front.animated.2bpp.lz"
AngoreBackpic:      INCBIN "gfx/pokemon/angore/back.2bpp.lz"
AppletunFrontpic:      INCBIN "gfx/pokemon/appletun/front.animated.2bpp.lz"
AppletunBackpic:      INCBIN "gfx/pokemon/appletun/back.2bpp.lz"
ApplinFrontpic:      INCBIN "gfx/pokemon/applin/front.animated.2bpp.lz"
ApplinBackpic:      INCBIN "gfx/pokemon/applin/back.2bpp.lz"
AraquanidFrontpic:      INCBIN "gfx/pokemon/araquanid/front.animated.2bpp.lz"
AraquanidBackpic:      INCBIN "gfx/pokemon/araquanid/back.2bpp.lz"
ArcanineFrontpic:      INCBIN "gfx/pokemon/arcanine/front.animated.2bpp.lz"
ArcanineBackpic:      INCBIN "gfx/pokemon/arcanine/back.2bpp.lz"
AronFrontpic:      INCBIN "gfx/pokemon/aron/front.animated.2bpp.lz"
AronBackpic:      INCBIN "gfx/pokemon/aron/back.2bpp.lz"
AurorusFrontpic:      INCBIN "gfx/pokemon/aurorus/front.animated.2bpp.lz"
AurorusBackpic:      INCBIN "gfx/pokemon/aurorus/back.2bpp.lz"
Bad_eggFrontpic:      INCBIN "gfx/pokemon/bad_egg/front.animated.2bpp.lz"
Bad_eggBackpic:      INCBIN "gfx/pokemon/bad_egg/back.2bpp.lz"
BarboachFrontpic:      INCBIN "gfx/pokemon/barboach/front.animated.2bpp.lz"
BarboachBackpic:      INCBIN "gfx/pokemon/barboach/back.2bpp.lz"
BeldumFrontpic:      INCBIN "gfx/pokemon/beldum/front.animated.2bpp.lz"
BeldumBackpic:      INCBIN "gfx/pokemon/beldum/back.2bpp.lz"
BewearFrontpic:      INCBIN "gfx/pokemon/bewear/front.animated.2bpp.lz"
BewearBackpic:      INCBIN "gfx/pokemon/bewear/back.2bpp.lz"
BlipbugFrontpic:      INCBIN "gfx/pokemon/blipbug/front.animated.2bpp.lz"
BlipbugBackpic:      INCBIN "gfx/pokemon/blipbug/back.2bpp.lz"
BlitzleFrontpic:      INCBIN "gfx/pokemon/blitzle/front.animated.2bpp.lz"
BlitzleBackpic:      INCBIN "gfx/pokemon/blitzle/back.2bpp.lz"


SECTION "Pics 7", ROMX

BoltundFrontpic:      INCBIN "gfx/pokemon/boltund/front.animated.2bpp.lz"
BoltundBackpic:      INCBIN "gfx/pokemon/boltund/back.2bpp.lz"
BoomerFrontpic:      INCBIN "gfx/pokemon/boomer/front.animated.2bpp.lz"
BoomerBackpic:      INCBIN "gfx/pokemon/boomer/back.2bpp.lz"
BouffalantFrontpic:      INCBIN "gfx/pokemon/bouffalant/front.animated.2bpp.lz"
BouffalantBackpic:      INCBIN "gfx/pokemon/bouffalant/back.2bpp.lz"
BounsweetFrontpic:      INCBIN "gfx/pokemon/bounsweet/front.animated.2bpp.lz"
BounsweetBackpic:      INCBIN "gfx/pokemon/bounsweet/back.2bpp.lz"
BreloomFrontpic:      INCBIN "gfx/pokemon/breloom/front.animated.2bpp.lz"
BreloomBackpic:      INCBIN "gfx/pokemon/breloom/back.2bpp.lz"
BruxishFrontpic:      INCBIN "gfx/pokemon/bruxish/front.animated.2bpp.lz"
BruxishBackpic:      INCBIN "gfx/pokemon/bruxish/back.2bpp.lz"
BuizelFrontpic:      INCBIN "gfx/pokemon/buizel/front.animated.2bpp.lz"
BuizelBackpic:      INCBIN "gfx/pokemon/buizel/back.2bpp.lz"
BurgelaFrontpic:      INCBIN "gfx/pokemon/burgela/front.animated.2bpp.lz"
BurgelaBackpic:      INCBIN "gfx/pokemon/burgela/back.2bpp.lz"
MewthreeFrontpic:      INCBIN "gfx/pokemon/mewthree/front.animated.2bpp.lz"
MewthreeBackpic:      INCBIN "gfx/pokemon/mewthree/back.2bpp.lz"
CarracostaFrontpic:      INCBIN "gfx/pokemon/carracosta/front.animated.2bpp.lz"
CarracostaBackpic:      INCBIN "gfx/pokemon/carracosta/back.2bpp.lz"
CentiskorchFrontpic:      INCBIN "gfx/pokemon/centiskorch/front.animated.2bpp.lz"
CentiskorchBackpic:      INCBIN "gfx/pokemon/centiskorch/back.2bpp.lz"
ChandelureFrontpic:      INCBIN "gfx/pokemon/chandelure/front.animated.2bpp.lz"
ChandelureBackpic:      INCBIN "gfx/pokemon/chandelure/back.2bpp.lz"
CharjabugFrontpic:      INCBIN "gfx/pokemon/charjabug/front.animated.2bpp.lz"
CharjabugBackpic:      INCBIN "gfx/pokemon/charjabug/back.2bpp.lz"
ChatotFrontpic:      INCBIN "gfx/pokemon/chatot/front.animated.2bpp.lz"
ChatotBackpic:      INCBIN "gfx/pokemon/chatot/back.2bpp.lz"
CherrimFrontpic:      INCBIN "gfx/pokemon/cherrim/front.animated.2bpp.lz"
CherrimBackpic:      INCBIN "gfx/pokemon/cherrim/back.2bpp.lz"
CherubiFrontpic:      INCBIN "gfx/pokemon/cherubi/front.animated.2bpp.lz"
CherubiBackpic:      INCBIN "gfx/pokemon/cherubi/back.2bpp.lz"
ChinchouFrontpic:      INCBIN "gfx/pokemon/chinchou/front.animated.2bpp.lz"
ChinchouBackpic:      INCBIN "gfx/pokemon/chinchou/back.2bpp.lz"
ClauncherFrontpic:      INCBIN "gfx/pokemon/clauncher/front.animated.2bpp.lz"
ClauncherBackpic:      INCBIN "gfx/pokemon/clauncher/back.2bpp.lz"


SECTION "Pics 8", ROMX

ClawitzerFrontpic:      INCBIN "gfx/pokemon/clawitzer/front.animated.2bpp.lz"
ClawitzerBackpic:      INCBIN "gfx/pokemon/clawitzer/back.2bpp.lz"
ClobbopusFrontpic:      INCBIN "gfx/pokemon/clobbopus/front.animated.2bpp.lz"
ClobbopusBackpic:      INCBIN "gfx/pokemon/clobbopus/back.2bpp.lz"
CorviknightFrontpic:      INCBIN "gfx/pokemon/corviknight/front.animated.2bpp.lz"
CorviknightBackpic:      INCBIN "gfx/pokemon/corviknight/back.2bpp.lz"
CorvisquireFrontpic:      INCBIN "gfx/pokemon/corvisquire/front.animated.2bpp.lz"
CorvisquireBackpic:      INCBIN "gfx/pokemon/corvisquire/back.2bpp.lz"
CroagunkFrontpic:      INCBIN "gfx/pokemon/croagunk/front.animated.2bpp.lz"
CroagunkBackpic:      INCBIN "gfx/pokemon/croagunk/back.2bpp.lz"
CrustleFrontpic:      INCBIN "gfx/pokemon/crustle/front.animated.2bpp.lz"
CrustleBackpic:      INCBIN "gfx/pokemon/crustle/back.2bpp.lz"
CryptiidFrontpic:      INCBIN "gfx/pokemon/cryptiid/front.animated.2bpp.lz"
CryptiidBackpic:      INCBIN "gfx/pokemon/cryptiid/back.2bpp.lz"
DaisyFrontpic:      INCBIN "gfx/pokemon/daisy/front.animated.2bpp.lz"
DaisyBackpic:      INCBIN "gfx/pokemon/daisy/back.2bpp.lz"
DeerlingFrontpic:      INCBIN "gfx/pokemon/deerling/front.animated.2bpp.lz"
DeerlingBackpic:      INCBIN "gfx/pokemon/deerling/back.2bpp.lz"
DelcattyFrontpic:      INCBIN "gfx/pokemon/delcatty/front.animated.2bpp.lz"
DelcattyBackpic:      INCBIN "gfx/pokemon/delcatty/back.2bpp.lz"
DewpiderFrontpic:      INCBIN "gfx/pokemon/dewpider/front.animated.2bpp.lz"
DewpiderBackpic:      INCBIN "gfx/pokemon/dewpider/back.2bpp.lz"
DittoFrontpic:      INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
DittoBackpic:      INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
DoomstoneFrontpic:      INCBIN "gfx/pokemon/doomstone/front.animated.2bpp.lz"
DoomstoneBackpic:      INCBIN "gfx/pokemon/doomstone/back.2bpp.lz"
DottlerFrontpic:      INCBIN "gfx/pokemon/dottler/front.animated.2bpp.lz"
DottlerBackpic:      INCBIN "gfx/pokemon/dottler/back.2bpp.lz"
VolcaronaFrontpic:      INCBIN "gfx/pokemon/volcarona/front.animated.2bpp.lz"
VolcaronaBackpic:      INCBIN "gfx/pokemon/volcarona/back.2bpp.lz"
DragalgeFrontpic:      INCBIN "gfx/pokemon/dragalge/front.animated.2bpp.lz"
DragalgeBackpic:      INCBIN "gfx/pokemon/dragalge/back.2bpp.lz"
DragapultFrontpic:      INCBIN "gfx/pokemon/dragapult/front.animated.2bpp.lz"
DragapultBackpic:      INCBIN "gfx/pokemon/dragapult/back.2bpp.lz"
DrakloakFrontpic:      INCBIN "gfx/pokemon/drakloak/front.animated.2bpp.lz"
DrakloakBackpic:      INCBIN "gfx/pokemon/drakloak/back.2bpp.lz"


SECTION "Pics 9", ROMX

DrampaFrontpic:      INCBIN "gfx/pokemon/drampa/front.animated.2bpp.lz"
DrampaBackpic:      INCBIN "gfx/pokemon/drampa/back.2bpp.lz"
DreepyFrontpic:      INCBIN "gfx/pokemon/dreepy/front.animated.2bpp.lz"
DreepyBackpic:      INCBIN "gfx/pokemon/dreepy/back.2bpp.lz"
DrilburFrontpic:      INCBIN "gfx/pokemon/drilbur/front.animated.2bpp.lz"
DrilburBackpic:      INCBIN "gfx/pokemon/drilbur/back.2bpp.lz"
DubwoolFrontpic:      INCBIN "gfx/pokemon/dubwool/front.animated.2bpp.lz"
DubwoolBackpic:      INCBIN "gfx/pokemon/dubwool/back.2bpp.lz"
DuosionFrontpic:      INCBIN "gfx/pokemon/duosion/front.animated.2bpp.lz"
DuosionBackpic:      INCBIN "gfx/pokemon/duosion/back.2bpp.lz"
DurantFrontpic:      INCBIN "gfx/pokemon/durant/front.animated.2bpp.lz"
DurantBackpic:      INCBIN "gfx/pokemon/durant/back.2bpp.lz"
DwebbleFrontpic:      INCBIN "gfx/pokemon/dwebble/front.animated.2bpp.lz"
DwebbleBackpic:      INCBIN "gfx/pokemon/dwebble/back.2bpp.lz"
EeveeFrontpic:      INCBIN "gfx/pokemon/eevee/front.animated.2bpp.lz"
EeveeBackpic:      INCBIN "gfx/pokemon/eevee/back.2bpp.lz"
EmolgaFrontpic:      INCBIN "gfx/pokemon/emolga/front.animated.2bpp.lz"
EmolgaBackpic:      INCBIN "gfx/pokemon/emolga/back.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
EspeonBackpic:      INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
EspurrFrontpic:      INCBIN "gfx/pokemon/espurr/front.animated.2bpp.lz"
EspurrBackpic:      INCBIN "gfx/pokemon/espurr/back.2bpp.lz"
ExcadrillFrontpic:      INCBIN "gfx/pokemon/excadrill/front.animated.2bpp.lz"
ExcadrillBackpic:      INCBIN "gfx/pokemon/excadrill/back.2bpp.lz"
ExeggcuteFrontpic:      INCBIN "gfx/pokemon/exeggcute/front.animated.2bpp.lz"
ExeggcuteBackpic:      INCBIN "gfx/pokemon/exeggcute/back.2bpp.lz"
ExeggutorFrontpic:      INCBIN "gfx/pokemon/exeggutor/front.animated.2bpp.lz"
ExeggutorBackpic:      INCBIN "gfx/pokemon/exeggutor/back.2bpp.lz"
FarfetchdFrontpic:      INCBIN "gfx/pokemon/farfetchd/front.animated.2bpp.lz"
FarfetchdBackpic:      INCBIN "gfx/pokemon/farfetchd/back.2bpp.lz"
FinneonFrontpic:      INCBIN "gfx/pokemon/finneon/front.animated.2bpp.lz"
FinneonBackpic:      INCBIN "gfx/pokemon/finneon/back.2bpp.lz"
FlappleFrontpic:      INCBIN "gfx/pokemon/flapple/front.animated.2bpp.lz"
FlappleBackpic:      INCBIN "gfx/pokemon/flapple/back.2bpp.lz"
FlareonFrontpic:      INCBIN "gfx/pokemon/flareon/front.animated.2bpp.lz"
FlareonBackpic:      INCBIN "gfx/pokemon/flareon/back.2bpp.lz"


SECTION "Pics 10", ROMX

FloatzelFrontpic:      INCBIN "gfx/pokemon/floatzel/front.animated.2bpp.lz"
FloatzelBackpic:      INCBIN "gfx/pokemon/floatzel/back.2bpp.lz"
FomantisFrontpic:      INCBIN "gfx/pokemon/fomantis/front.animated.2bpp.lz"
FomantisBackpic:      INCBIN "gfx/pokemon/fomantis/back.2bpp.lz"
FrosmothFrontpic:      INCBIN "gfx/pokemon/frosmoth/front.animated.2bpp.lz"
FrosmothBackpic:      INCBIN "gfx/pokemon/frosmoth/back.2bpp.lz"
FuriousbFrontpic:      INCBIN "gfx/pokemon/furiousb/front.animated.2bpp.lz"
FuriousbBackpic:      INCBIN "gfx/pokemon/furiousb/back.2bpp.lz"
GalladeFrontpic:      INCBIN "gfx/pokemon/gallade/front.animated.2bpp.lz"
GalladeBackpic:      INCBIN "gfx/pokemon/gallade/back.2bpp.lz"
BuzzeonFrontpic:      INCBIN "gfx/pokemon/buzzeon/front.animated.2bpp.lz"
BuzzeonBackpic:      INCBIN "gfx/pokemon/buzzeon/back.2bpp.lz"
GarbodorFrontpic:      INCBIN "gfx/pokemon/garbodor/front.animated.2bpp.lz"
GarbodorBackpic:      INCBIN "gfx/pokemon/garbodor/back.2bpp.lz"
GardevoirFrontpic:      INCBIN "gfx/pokemon/gardevoir/front.animated.2bpp.lz"
GardevoirBackpic:      INCBIN "gfx/pokemon/gardevoir/back.2bpp.lz"
GastlyFrontpic:      INCBIN "gfx/pokemon/gastly/front.animated.2bpp.lz"
GastlyBackpic:      INCBIN "gfx/pokemon/gastly/back.2bpp.lz"
GastrodonFrontpic:      INCBIN "gfx/pokemon/gastrodon/front.animated.2bpp.lz"
GastrodonBackpic:      INCBIN "gfx/pokemon/gastrodon/back.2bpp.lz"
GengarFrontpic:      INCBIN "gfx/pokemon/gengar/front.animated.2bpp.lz"
GengarBackpic:      INCBIN "gfx/pokemon/gengar/back.2bpp.lz"
GlaceonFrontpic:      INCBIN "gfx/pokemon/glaceon/front.animated.2bpp.lz"
GlaceonBackpic:      INCBIN "gfx/pokemon/glaceon/back.2bpp.lz"
GrapploctFrontpic:      INCBIN "gfx/pokemon/grapploct/front.animated.2bpp.lz"
GrapploctBackpic:      INCBIN "gfx/pokemon/grapploct/back.2bpp.lz"
GrenmarFrontpic:      INCBIN "gfx/pokemon/grenmar/front.animated.2bpp.lz"
GrenmarBackpic:      INCBIN "gfx/pokemon/grenmar/back.2bpp.lz"
GrimerFrontpic:      INCBIN "gfx/pokemon/grimer/front.animated.2bpp.lz"
GrimerBackpic:      INCBIN "gfx/pokemon/grimer/back.2bpp.lz"
GrowlitheFrontpic:      INCBIN "gfx/pokemon/growlithe/front.animated.2bpp.lz"
GrowlitheBackpic:      INCBIN "gfx/pokemon/growlithe/back.2bpp.lz"
GrubbinFrontpic:      INCBIN "gfx/pokemon/grubbin/front.animated.2bpp.lz"
GrubbinBackpic:      INCBIN "gfx/pokemon/grubbin/back.2bpp.lz"
GumshoosFrontpic:      INCBIN "gfx/pokemon/gumshoos/front.animated.2bpp.lz"
GumshoosBackpic:      INCBIN "gfx/pokemon/gumshoos/back.2bpp.lz"


SECTION "Pics 11", ROMX

Hakamo_oFrontpic:      INCBIN "gfx/pokemon/hakamo_o/front.animated.2bpp.lz"
Hakamo_oBackpic:      INCBIN "gfx/pokemon/hakamo_o/back.2bpp.lz"
HariyamaFrontpic:      INCBIN "gfx/pokemon/hariyama/front.animated.2bpp.lz"
HariyamaBackpic:      INCBIN "gfx/pokemon/hariyama/back.2bpp.lz"
HatennaFrontpic:      INCBIN "gfx/pokemon/hatenna/front.animated.2bpp.lz"
HatennaBackpic:      INCBIN "gfx/pokemon/hatenna/back.2bpp.lz"
HattereneFrontpic:      INCBIN "gfx/pokemon/hatterene/front.animated.2bpp.lz"
HattereneBackpic:      INCBIN "gfx/pokemon/hatterene/back.2bpp.lz"
HattremFrontpic:      INCBIN "gfx/pokemon/hattrem/front.animated.2bpp.lz"
HattremBackpic:      INCBIN "gfx/pokemon/hattrem/back.2bpp.lz"
HaunterFrontpic:      INCBIN "gfx/pokemon/haunter/front.animated.2bpp.lz"
HaunterBackpic:      INCBIN "gfx/pokemon/haunter/back.2bpp.lz"
HeatmorFrontpic:      INCBIN "gfx/pokemon/heatmor/front.animated.2bpp.lz"
HeatmorBackpic:      INCBIN "gfx/pokemon/heatmor/back.2bpp.lz"
HeracrossFrontpic:      INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"
HeracrossBackpic:      INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
HerdierFrontpic:      INCBIN "gfx/pokemon/herdier/front.animated.2bpp.lz"
HerdierBackpic:      INCBIN "gfx/pokemon/herdier/back.2bpp.lz"
LarvestaFrontpic:      INCBIN "gfx/pokemon/larvesta/front.animated.2bpp.lz"
LarvestaBackpic:      INCBIN "gfx/pokemon/larvesta/back.2bpp.lz"
HoppipFrontpic:      INCBIN "gfx/pokemon/hoppip/front.animated.2bpp.lz"
HoppipBackpic:      INCBIN "gfx/pokemon/hoppip/back.2bpp.lz"
HoundoomFrontpic:      INCBIN "gfx/pokemon/houndoom/front.animated.2bpp.lz"
HoundoomBackpic:      INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
HoundourFrontpic:      INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
HoundourBackpic:      INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
Jangmo_oFrontpic:      INCBIN "gfx/pokemon/jangmo_o/front.animated.2bpp.lz"
Jangmo_oBackpic:      INCBIN "gfx/pokemon/jangmo_o/back.2bpp.lz"
JolteonFrontpic:      INCBIN "gfx/pokemon/jolteon/front.animated.2bpp.lz"
JolteonBackpic:      INCBIN "gfx/pokemon/jolteon/back.2bpp.lz"
VespiquenFrontpic:      INCBIN "gfx/pokemon/vespiquen/front.animated.2bpp.lz"
VespiquenBackpic:      INCBIN "gfx/pokemon/vespiquen/back.2bpp.lz"
JumpluffFrontpic:      INCBIN "gfx/pokemon/jumpluff/front.animated.2bpp.lz"
JumpluffBackpic:      INCBIN "gfx/pokemon/jumpluff/back.2bpp.lz"
JungelaFrontpic:      INCBIN "gfx/pokemon/jungela/front.animated.2bpp.lz"
JungelaBackpic:      INCBIN "gfx/pokemon/jungela/back.2bpp.lz"


SECTION "Pics 12", ROMX

KirbyFrontpic:      INCBIN "gfx/pokemon/kirby/front.animated.2bpp.lz"
KirbyBackpic:      INCBIN "gfx/pokemon/kirby/back.2bpp.lz"
KirliaFrontpic:      INCBIN "gfx/pokemon/kirlia/front.animated.2bpp.lz"
KirliaBackpic:      INCBIN "gfx/pokemon/kirlia/back.2bpp.lz"
KleavorFrontpic:      INCBIN "gfx/pokemon/kleavor/front.animated.2bpp.lz"
KleavorBackpic:      INCBIN "gfx/pokemon/kleavor/back.2bpp.lz"
KoffingFrontpic:      INCBIN "gfx/pokemon/koffing/front.animated.2bpp.lz"
KoffingBackpic:      INCBIN "gfx/pokemon/koffing/back.2bpp.lz"
Kommo_oFrontpic:      INCBIN "gfx/pokemon/kommo_o/front.animated.2bpp.lz"
Kommo_oBackpic:      INCBIN "gfx/pokemon/kommo_o/back.2bpp.lz"
LaironFrontpic:      INCBIN "gfx/pokemon/lairon/front.animated.2bpp.lz"
LaironBackpic:      INCBIN "gfx/pokemon/lairon/back.2bpp.lz"
LampentFrontpic:      INCBIN "gfx/pokemon/lampent/front.animated.2bpp.lz"
LampentBackpic:      INCBIN "gfx/pokemon/lampent/back.2bpp.lz"
LanturnFrontpic:      INCBIN "gfx/pokemon/lanturn/front.animated.2bpp.lz"
LanturnBackpic:      INCBIN "gfx/pokemon/lanturn/back.2bpp.lz"
LaprasFrontpic:      INCBIN "gfx/pokemon/lapras/front.animated.2bpp.lz"
LaprasBackpic:      INCBIN "gfx/pokemon/lapras/back.2bpp.lz"
LarvitarFrontpic:      INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
LarvitarBackpic:      INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
LeafeonFrontpic:      INCBIN "gfx/pokemon/leafeon/front.animated.2bpp.lz"
LeafeonBackpic:      INCBIN "gfx/pokemon/leafeon/back.2bpp.lz"
LiepardFrontpic:      INCBIN "gfx/pokemon/liepard/front.animated.2bpp.lz"
LiepardBackpic:      INCBIN "gfx/pokemon/liepard/back.2bpp.lz"
LillipupFrontpic:      INCBIN "gfx/pokemon/lillipup/front.animated.2bpp.lz"
LillipupBackpic:      INCBIN "gfx/pokemon/lillipup/back.2bpp.lz"
LinooneFrontpic:      INCBIN "gfx/pokemon/linoone/front.animated.2bpp.lz"
LinooneBackpic:      INCBIN "gfx/pokemon/linoone/back.2bpp.lz"
LitleoFrontpic:      INCBIN "gfx/pokemon/litleo/front.animated.2bpp.lz"
LitleoBackpic:      INCBIN "gfx/pokemon/litleo/back.2bpp.lz"
LitwickFrontpic:      INCBIN "gfx/pokemon/litwick/front.animated.2bpp.lz"
LitwickBackpic:      INCBIN "gfx/pokemon/litwick/back.2bpp.lz"
LombreFrontpic:      INCBIN "gfx/pokemon/lombre/front.animated.2bpp.lz"
LombreBackpic:      INCBIN "gfx/pokemon/lombre/back.2bpp.lz"
LotadFrontpic:      INCBIN "gfx/pokemon/lotad/front.animated.2bpp.lz"
LotadBackpic:      INCBIN "gfx/pokemon/lotad/back.2bpp.lz"


SECTION "Pics 13", ROMX

LudicoloFrontpic:      INCBIN "gfx/pokemon/ludicolo/front.animated.2bpp.lz"
LudicoloBackpic:      INCBIN "gfx/pokemon/ludicolo/back.2bpp.lz"
LumineonFrontpic:      INCBIN "gfx/pokemon/lumineon/front.animated.2bpp.lz"
LumineonBackpic:      INCBIN "gfx/pokemon/lumineon/back.2bpp.lz"
LurantisFrontpic:      INCBIN "gfx/pokemon/lurantis/front.animated.2bpp.lz"
LurantisBackpic:      INCBIN "gfx/pokemon/lurantis/back.2bpp.lz"
LuxwanFrontpic:      INCBIN "gfx/pokemon/luxwan/front.animated.2bpp.lz"
LuxwanBackpic:      INCBIN "gfx/pokemon/luxwan/back.2bpp.lz"
Lycanroc_duskFrontpic:      INCBIN "gfx/pokemon/lycanroc_dusk/front.animated.2bpp.lz"
Lycanroc_duskBackpic:      INCBIN "gfx/pokemon/lycanroc_dusk/back.2bpp.lz"
Lycanroc_middayFrontpic:      INCBIN "gfx/pokemon/lycanroc_midday/front.animated.2bpp.lz"
Lycanroc_middayBackpic:      INCBIN "gfx/pokemon/lycanroc_midday/back.2bpp.lz"
Lycanroc_midnightFrontpic:      INCBIN "gfx/pokemon/lycanroc_midnight/front.animated.2bpp.lz"
Lycanroc_midnightBackpic:      INCBIN "gfx/pokemon/lycanroc_midnight/back.2bpp.lz"
M_blockFrontpic:      INCBIN "gfx/pokemon/m_block/front.animated.2bpp.lz"
M_blockBackpic:      INCBIN "gfx/pokemon/m_block/back.2bpp.lz"
MakuhitaFrontpic:      INCBIN "gfx/pokemon/makuhita/front.animated.2bpp.lz"
MakuhitaBackpic:      INCBIN "gfx/pokemon/makuhita/back.2bpp.lz"
MamoswineFrontpic:      INCBIN "gfx/pokemon/mamoswine/front.animated.2bpp.lz"
MamoswineBackpic:      INCBIN "gfx/pokemon/mamoswine/back.2bpp.lz"
MareanieFrontpic:      INCBIN "gfx/pokemon/mareanie/front.animated.2bpp.lz"
MareanieBackpic:      INCBIN "gfx/pokemon/mareanie/back.2bpp.lz"
MawileFrontpic:      INCBIN "gfx/pokemon/mawile/front.animated.2bpp.lz"
MawileBackpic:      INCBIN "gfx/pokemon/mawile/back.2bpp.lz"
Mega_gengarFrontpic:      INCBIN "gfx/pokemon/mega_gengar/front.animated.2bpp.lz"
Mega_gengarBackpic:      INCBIN "gfx/pokemon/mega_gengar/back.2bpp.lz"
Mega_mawileFrontpic:      INCBIN "gfx/pokemon/mega_mawile/front.animated.2bpp.lz"
Mega_mawileBackpic:      INCBIN "gfx/pokemon/mega_mawile/back.2bpp.lz"
Meowstic_fFrontpic:      INCBIN "gfx/pokemon/meowstic_f/front.animated.2bpp.lz"
Meowstic_fBackpic:      INCBIN "gfx/pokemon/meowstic_f/back.2bpp.lz"
Meowstic_mFrontpic:      INCBIN "gfx/pokemon/meowstic_m/front.animated.2bpp.lz"
Meowstic_mBackpic:      INCBIN "gfx/pokemon/meowstic_m/back.2bpp.lz"
MeowthFrontpic:      INCBIN "gfx/pokemon/meowth/front.animated.2bpp.lz"
MeowthBackpic:      INCBIN "gfx/pokemon/meowth/back.2bpp.lz"
MetagrossFrontpic:      INCBIN "gfx/pokemon/metagross/front.animated.2bpp.lz"
MetagrossBackpic:      INCBIN "gfx/pokemon/metagross/back.2bpp.lz"


SECTION "Pics 14", ROMX

MetangFrontpic:      INCBIN "gfx/pokemon/metang/front.animated.2bpp.lz"
MetangBackpic:      INCBIN "gfx/pokemon/metang/back.2bpp.lz"
Minior_coreFrontpic:      INCBIN "gfx/pokemon/minior_core/front.animated.2bpp.lz"
Minior_coreBackpic:      INCBIN "gfx/pokemon/minior_core/back.2bpp.lz"
Minior_meteorFrontpic:      INCBIN "gfx/pokemon/minior_meteor/front.animated.2bpp.lz"
Minior_meteorBackpic:      INCBIN "gfx/pokemon/minior_meteor/back.2bpp.lz"
MisdreavusFrontpic:      INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
MisdreavusBackpic:      INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
MismagiusFrontpic:      INCBIN "gfx/pokemon/mismagius/front.animated.2bpp.lz"
MismagiusBackpic:      INCBIN "gfx/pokemon/mismagius/back.2bpp.lz"
MolambinoFrontpic:      INCBIN "gfx/pokemon/molambino/front.animated.2bpp.lz"
MolambinoBackpic:      INCBIN "gfx/pokemon/molambino/back.2bpp.lz"
MorelullFrontpic:      INCBIN "gfx/pokemon/morelull/front.animated.2bpp.lz"
MorelullBackpic:      INCBIN "gfx/pokemon/morelull/back.2bpp.lz"
MudbrayFrontpic:      INCBIN "gfx/pokemon/mudbray/front.animated.2bpp.lz"
MudbrayBackpic:      INCBIN "gfx/pokemon/mudbray/back.2bpp.lz"
MudsdaleFrontpic:      INCBIN "gfx/pokemon/mudsdale/front.animated.2bpp.lz"
MudsdaleBackpic:      INCBIN "gfx/pokemon/mudsdale/back.2bpp.lz"
MukFrontpic:      INCBIN "gfx/pokemon/muk/front.animated.2bpp.lz"
MukBackpic:      INCBIN "gfx/pokemon/muk/back.2bpp.lz"
MunnaFrontpic:      INCBIN "gfx/pokemon/munna/front.animated.2bpp.lz"
MunnaBackpic:      INCBIN "gfx/pokemon/munna/back.2bpp.lz"
MusharnaFrontpic:      INCBIN "gfx/pokemon/musharna/front.animated.2bpp.lz"
MusharnaBackpic:      INCBIN "gfx/pokemon/musharna/back.2bpp.lz"
NoibatFrontpic:      INCBIN "gfx/pokemon/noibat/front.animated.2bpp.lz"
NoibatBackpic:      INCBIN "gfx/pokemon/noibat/back.2bpp.lz"
NoivernFrontpic:      INCBIN "gfx/pokemon/noivern/front.animated.2bpp.lz"
NoivernBackpic:      INCBIN "gfx/pokemon/noivern/back.2bpp.lz"
ObstagoonFrontpic:      INCBIN "gfx/pokemon/obstagoon/front.animated.2bpp.lz"
ObstagoonBackpic:      INCBIN "gfx/pokemon/obstagoon/back.2bpp.lz"
OranguruFrontpic:      INCBIN "gfx/pokemon/oranguru/front.animated.2bpp.lz"
OranguruBackpic:      INCBIN "gfx/pokemon/oranguru/back.2bpp.lz"
OrbeetleFrontpic:      INCBIN "gfx/pokemon/orbeetle/front.animated.2bpp.lz"
OrbeetleBackpic:      INCBIN "gfx/pokemon/orbeetle/back.2bpp.lz"
Oricorio_baileFrontpic:      INCBIN "gfx/pokemon/oricorio_baile/front.animated.2bpp.lz"
Oricorio_baileBackpic:      INCBIN "gfx/pokemon/oricorio_baile/back.2bpp.lz"


SECTION "Pics 15", ROMX

Oricorio_pauFrontpic:      INCBIN "gfx/pokemon/oricorio_pau/front.animated.2bpp.lz"
Oricorio_pauBackpic:      INCBIN "gfx/pokemon/oricorio_pau/back.2bpp.lz"
Oricorio_pomFrontpic:      INCBIN "gfx/pokemon/oricorio_pom/front.animated.2bpp.lz"
Oricorio_pomBackpic:      INCBIN "gfx/pokemon/oricorio_pom/back.2bpp.lz"
Oricorio_sensuFrontpic:      INCBIN "gfx/pokemon/oricorio_sensu/front.animated.2bpp.lz"
Oricorio_sensuBackpic:      INCBIN "gfx/pokemon/oricorio_sensu/back.2bpp.lz"
PalossandFrontpic:      INCBIN "gfx/pokemon/palossand/front.animated.2bpp.lz"
PalossandBackpic:      INCBIN "gfx/pokemon/palossand/back.2bpp.lz"
PalpitoadFrontpic:      INCBIN "gfx/pokemon/palpitoad/front.animated.2bpp.lz"
PalpitoadBackpic:      INCBIN "gfx/pokemon/palpitoad/back.2bpp.lz"
RegimagmaFrontpic:      INCBIN "gfx/pokemon/regimagma/front.animated.2bpp.lz"
RegimagmaBackpic:      INCBIN "gfx/pokemon/regimagma/back.2bpp.lz"
PerrserkerFrontpic:      INCBIN "gfx/pokemon/perrserker/front.animated.2bpp.lz"
PerrserkerBackpic:      INCBIN "gfx/pokemon/perrserker/back.2bpp.lz"
PikipekFrontpic:      INCBIN "gfx/pokemon/pikipek/front.animated.2bpp.lz"
PikipekBackpic:      INCBIN "gfx/pokemon/pikipek/back.2bpp.lz"
PiloswineFrontpic:      INCBIN "gfx/pokemon/piloswine/front.animated.2bpp.lz"
PiloswineBackpic:      INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
PonytaFrontpic:      INCBIN "gfx/pokemon/ponyta/front.animated.2bpp.lz"
PonytaBackpic:      INCBIN "gfx/pokemon/ponyta/back.2bpp.lz"
PoppyFrontpic:      INCBIN "gfx/pokemon/poppy/front.animated.2bpp.lz"
PoppyBackpic:      INCBIN "gfx/pokemon/poppy/back.2bpp.lz"
PorygonFrontpic:      INCBIN "gfx/pokemon/porygon/front.animated.2bpp.lz"
PorygonBackpic:      INCBIN "gfx/pokemon/porygon/back.2bpp.lz"
Porygon2Frontpic:      INCBIN "gfx/pokemon/porygon2/front.animated.2bpp.lz"
Porygon2Backpic:      INCBIN "gfx/pokemon/porygon2/back.2bpp.lz"
Porygon_zFrontpic:      INCBIN "gfx/pokemon/porygon_z/front.animated.2bpp.lz"
Porygon_zBackpic:      INCBIN "gfx/pokemon/porygon_z/back.2bpp.lz"
PupitarFrontpic:      INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
PurrloinFrontpic:      INCBIN "gfx/pokemon/purrloin/front.animated.2bpp.lz"
PurrloinBackpic:      INCBIN "gfx/pokemon/purrloin/back.2bpp.lz"
PyroarFrontpic:      INCBIN "gfx/pokemon/pyroar/front.animated.2bpp.lz"
PyroarBackpic:      INCBIN "gfx/pokemon/pyroar/back.2bpp.lz"
RaltsFrontpic:      INCBIN "gfx/pokemon/ralts/front.animated.2bpp.lz"
RaltsBackpic:      INCBIN "gfx/pokemon/ralts/back.2bpp.lz"


SECTION "Pics 16", ROMX


RapidashFrontpic:      INCBIN "gfx/pokemon/rapidash/front.animated.2bpp.lz"
RapidashBackpic:      INCBIN "gfx/pokemon/rapidash/back.2bpp.lz"
ReuniclusFrontpic:      INCBIN "gfx/pokemon/reuniclus/front.animated.2bpp.lz"
ReuniclusBackpic:      INCBIN "gfx/pokemon/reuniclus/back.2bpp.lz"
RockruffFrontpic:      INCBIN "gfx/pokemon/rockruff/front.animated.2bpp.lz"
RockruffBackpic:      INCBIN "gfx/pokemon/rockruff/back.2bpp.lz"
RookideeFrontpic:      INCBIN "gfx/pokemon/rookidee/front.animated.2bpp.lz"
RookideeBackpic:      INCBIN "gfx/pokemon/rookidee/back.2bpp.lz"
SalanditFrontpic:      INCBIN "gfx/pokemon/salandit/front.animated.2bpp.lz"
Salandit2Frontpic:      INCBIN "gfx/pokemon/salandit2/front.animated.2bpp.lz"
SalanditBackpic:      INCBIN "gfx/pokemon/salandit/back.2bpp.lz"
Salandit2Backpic:      INCBIN "gfx/pokemon/salandit/back.2bpp.lz"
SalazzleFrontpic:      INCBIN "gfx/pokemon/salazzle/front.animated.2bpp.lz"
Salazzle2Frontpic:      INCBIN "gfx/pokemon/salazzle2/front.animated.2bpp.lz"
SalazzleBackpic:      INCBIN "gfx/pokemon/salazzle/back.2bpp.lz"
Salazzle2Backpic:      INCBIN "gfx/pokemon/salazzle/back.2bpp.lz"
SandygastFrontpic:      INCBIN "gfx/pokemon/sandygast/front.animated.2bpp.lz"
SandygastBackpic:      INCBIN "gfx/pokemon/sandygast/back.2bpp.lz"
SawsbuckFrontpic:      INCBIN "gfx/pokemon/sawsbuck/front.animated.2bpp.lz"
SawsbuckBackpic:      INCBIN "gfx/pokemon/sawsbuck/back.2bpp.lz"
ScizorFrontpic:      INCBIN "gfx/pokemon/scizor/front.animated.2bpp.lz"
ScizorBackpic:      INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
ScytherFrontpic:      INCBIN "gfx/pokemon/scyther/front.animated.2bpp.lz"
ScytherBackpic:      INCBIN "gfx/pokemon/scyther/back.2bpp.lz"
SealeoFrontpic:      INCBIN "gfx/pokemon/sealeo/front.animated.2bpp.lz"
SealeoBackpic:      INCBIN "gfx/pokemon/sealeo/back.2bpp.lz"
SeismitoadFrontpic:      INCBIN "gfx/pokemon/seismitoad/front.animated.2bpp.lz"
SeismitoadBackpic:      INCBIN "gfx/pokemon/seismitoad/back.2bpp.lz"
ShellosFrontpic:      INCBIN "gfx/pokemon/shellos/front.animated.2bpp.lz"
ShellosBackpic:      INCBIN "gfx/pokemon/shellos/back.2bpp.lz"
ShiinoticFrontpic:      INCBIN "gfx/pokemon/shiinotic/front.animated.2bpp.lz"
ShiinoticBackpic:      INCBIN "gfx/pokemon/shiinotic/back.2bpp.lz"
ShroomishFrontpic:      INCBIN "gfx/pokemon/shroomish/front.animated.2bpp.lz"
ShroomishBackpic:      INCBIN "gfx/pokemon/shroomish/back.2bpp.lz"
SirfetchdFrontpic:      INCBIN "gfx/pokemon/sirfetchd/front.animated.2bpp.lz"
SirfetchdBackpic:      INCBIN "gfx/pokemon/sirfetchd/back.2bpp.lz"


SECTION "Pics 17", ROMX

SizzlipedeFrontpic:      INCBIN "gfx/pokemon/sizzlipede/front.animated.2bpp.lz"
SizzlipedeBackpic:      INCBIN "gfx/pokemon/sizzlipede/back.2bpp.lz"
SkarmoryFrontpic:      INCBIN "gfx/pokemon/skarmory/front.animated.2bpp.lz"
SkarmoryBackpic:      INCBIN "gfx/pokemon/skarmory/back.2bpp.lz"
SkiploomFrontpic:      INCBIN "gfx/pokemon/skiploom/front.animated.2bpp.lz"
SkiploomBackpic:      INCBIN "gfx/pokemon/skiploom/back.2bpp.lz"
SkittyFrontpic:      INCBIN "gfx/pokemon/skitty/front.animated.2bpp.lz"
SkittyBackpic:      INCBIN "gfx/pokemon/skitty/back.2bpp.lz"
SkrelpFrontpic:      INCBIN "gfx/pokemon/skrelp/front.animated.2bpp.lz"
SkrelpBackpic:      INCBIN "gfx/pokemon/skrelp/back.2bpp.lz"
SkuntankFrontpic:      INCBIN "gfx/pokemon/skuntank/front.animated.2bpp.lz"
SkuntankBackpic:      INCBIN "gfx/pokemon/skuntank/back.2bpp.lz"
SnomFrontpic:      INCBIN "gfx/pokemon/snom/front.animated.2bpp.lz"
SnomBackpic:      INCBIN "gfx/pokemon/snom/back.2bpp.lz"
SnorlaxFrontpic:      INCBIN "gfx/pokemon/snorlax/front.animated.2bpp.lz"
SnorlaxBackpic:      INCBIN "gfx/pokemon/snorlax/back.2bpp.lz"
SnoverFrontpic:      INCBIN "gfx/pokemon/snover/front.animated.2bpp.lz"
SnoverBackpic:      INCBIN "gfx/pokemon/snover/back.2bpp.lz"
SolosisFrontpic:      INCBIN "gfx/pokemon/solosis/front.animated.2bpp.lz"
SolosisBackpic:      INCBIN "gfx/pokemon/solosis/back.2bpp.lz"
SphealFrontpic:      INCBIN "gfx/pokemon/spheal/front.animated.2bpp.lz"
SphealBackpic:      INCBIN "gfx/pokemon/spheal/back.2bpp.lz"
SpirripFrontpic:      INCBIN "gfx/pokemon/spirrip/front.animated.2bpp.lz"
SpirripBackpic:      INCBIN "gfx/pokemon/spirrip/back.2bpp.lz"
StantlerFrontpic:      INCBIN "gfx/pokemon/stantler/front.animated.2bpp.lz"
StantlerBackpic:      INCBIN "gfx/pokemon/stantler/back.2bpp.lz"
SteeneeFrontpic:      INCBIN "gfx/pokemon/steenee/front.animated.2bpp.lz"
SteeneeBackpic:      INCBIN "gfx/pokemon/steenee/back.2bpp.lz"
StoutlandFrontpic:      INCBIN "gfx/pokemon/stoutland/front.animated.2bpp.lz"
StoutlandBackpic:      INCBIN "gfx/pokemon/stoutland/back.2bpp.lz"
StraigarFrontpic:      INCBIN "gfx/pokemon/straigar/front.animated.2bpp.lz"
StraigarBackpic:      INCBIN "gfx/pokemon/straigar/back.2bpp.lz"
StuffulFrontpic:      INCBIN "gfx/pokemon/stufful/front.animated.2bpp.lz"
StuffulBackpic:      INCBIN "gfx/pokemon/stufful/back.2bpp.lz"
StunkyFrontpic:      INCBIN "gfx/pokemon/stunky/front.animated.2bpp.lz"
StunkyBackpic:      INCBIN "gfx/pokemon/stunky/back.2bpp.lz"


SECTION "Pics 18", ROMX

SuicuneFrontpic:      INCBIN "gfx/pokemon/suicune/front.animated.2bpp.lz"
SuicuneBackpic:      INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
SwinubFrontpic:      INCBIN "gfx/pokemon/swinub/front.animated.2bpp.lz"
SwinubBackpic:      INCBIN "gfx/pokemon/swinub/back.2bpp.lz"
SwoobatFrontpic:      INCBIN "gfx/pokemon/swoobat/front.animated.2bpp.lz"
SwoobatBackpic:      INCBIN "gfx/pokemon/swoobat/back.2bpp.lz"
SylveonFrontpic:      INCBIN "gfx/pokemon/sylveon/front.animated.2bpp.lz"
SylveonBackpic:      INCBIN "gfx/pokemon/sylveon/back.2bpp.lz"
TangelaFrontpic:      INCBIN "gfx/pokemon/tangela/front.animated.2bpp.lz"
TangelaBackpic:      INCBIN "gfx/pokemon/tangela/back.2bpp.lz"
TangrowthFrontpic:      INCBIN "gfx/pokemon/tangrowth/front.animated.2bpp.lz"
TangrowthBackpic:      INCBIN "gfx/pokemon/tangrowth/back.2bpp.lz"
TeddiursaFrontpic:      INCBIN "gfx/pokemon/teddiursa/front.animated.2bpp.lz"
TeddiursaBackpic:      INCBIN "gfx/pokemon/teddiursa/back.2bpp.lz"
TirtougaFrontpic:      INCBIN "gfx/pokemon/tirtouga/front.animated.2bpp.lz"
TirtougaBackpic:      INCBIN "gfx/pokemon/tirtouga/back.2bpp.lz"
ToucannonFrontpic:      INCBIN "gfx/pokemon/toucannon/front.animated.2bpp.lz"
ToucannonBackpic:      INCBIN "gfx/pokemon/toucannon/back.2bpp.lz"
ToxapexFrontpic:      INCBIN "gfx/pokemon/toxapex/front.animated.2bpp.lz"
ToxapexBackpic:      INCBIN "gfx/pokemon/toxapex/back.2bpp.lz"
ToxicroakFrontpic:      INCBIN "gfx/pokemon/toxicroak/front.animated.2bpp.lz"
ToxicroakBackpic:      INCBIN "gfx/pokemon/toxicroak/back.2bpp.lz"
TrubbishFrontpic:      INCBIN "gfx/pokemon/trubbish/front.animated.2bpp.lz"
TrubbishBackpic:      INCBIN "gfx/pokemon/trubbish/back.2bpp.lz"
TrumbeakFrontpic:      INCBIN "gfx/pokemon/trumbeak/front.animated.2bpp.lz"
TrumbeakBackpic:      INCBIN "gfx/pokemon/trumbeak/back.2bpp.lz"
TsareenaFrontpic:      INCBIN "gfx/pokemon/tsareena/front.animated.2bpp.lz"
TsareenaBackpic:      INCBIN "gfx/pokemon/tsareena/back.2bpp.lz"
TykerFrontpic:      INCBIN "gfx/pokemon/tyker/front.animated.2bpp.lz"
TykerBackpic:      INCBIN "gfx/pokemon/tyker/back.2bpp.lz"
TympoleFrontpic:      INCBIN "gfx/pokemon/tympole/front.animated.2bpp.lz"
TympoleBackpic:      INCBIN "gfx/pokemon/tympole/back.2bpp.lz"
TyranitarFrontpic:      INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
TyranitarBackpic:      INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"


SECTION "Pics 19", ROMX

UmbreonFrontpic:      INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
UrsalunaFrontpic:      INCBIN "gfx/pokemon/ursaluna/front.animated.2bpp.lz"
UrsalunaBackpic:      INCBIN "gfx/pokemon/ursaluna/back.2bpp.lz"
UrsaringFrontpic:      INCBIN "gfx/pokemon/ursaring/front.animated.2bpp.lz"
UrsaringBackpic:      INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"
VaporeonFrontpic:      INCBIN "gfx/pokemon/vaporeon/front.animated.2bpp.lz"
VaporeonBackpic:      INCBIN "gfx/pokemon/vaporeon/back.2bpp.lz"
VikavoltFrontpic:      INCBIN "gfx/pokemon/vikavolt/front.animated.2bpp.lz"
VikavoltBackpic:      INCBIN "gfx/pokemon/vikavolt/back.2bpp.lz"
WalreinFrontpic:      INCBIN "gfx/pokemon/walrein/front.animated.2bpp.lz"
WalreinBackpic:      INCBIN "gfx/pokemon/walrein/back.2bpp.lz"
WeezingFrontpic:      INCBIN "gfx/pokemon/weezing/front.animated.2bpp.lz"
WeezingBackpic:      INCBIN "gfx/pokemon/weezing/back.2bpp.lz"
WhiscashFrontpic:      INCBIN "gfx/pokemon/whiscash/front.animated.2bpp.lz"
WhiscashBackpic:      INCBIN "gfx/pokemon/whiscash/back.2bpp.lz"
ChompFrontpic:      INCBIN "gfx/pokemon/chomp/front.animated.2bpp.lz"
ChompBackpic:      INCBIN "gfx/pokemon/chomp/back.2bpp.lz"
WoobatFrontpic:      INCBIN "gfx/pokemon/woobat/front.animated.2bpp.lz"
WoobatBackpic:      INCBIN "gfx/pokemon/woobat/back.2bpp.lz"
WoolooFrontpic:      INCBIN "gfx/pokemon/wooloo/front.animated.2bpp.lz"
WoolooBackpic:      INCBIN "gfx/pokemon/wooloo/back.2bpp.lz"
WyrdeerFrontpic:      INCBIN "gfx/pokemon/wyrdeer/front.animated.2bpp.lz"
WyrdeerBackpic:      INCBIN "gfx/pokemon/wyrdeer/back.2bpp.lz"
YamperFrontpic:      INCBIN "gfx/pokemon/yamper/front.animated.2bpp.lz"
YamperBackpic:      INCBIN "gfx/pokemon/yamper/back.2bpp.lz"
YanmaFrontpic:      INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
YanmaBackpic:      INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
YanmegaFrontpic:      INCBIN "gfx/pokemon/yanmega/front.animated.2bpp.lz"
YanmegaBackpic:      INCBIN "gfx/pokemon/yanmega/back.2bpp.lz"
YungoosFrontpic:      INCBIN "gfx/pokemon/yungoos/front.animated.2bpp.lz"
YungoosBackpic:      INCBIN "gfx/pokemon/yungoos/back.2bpp.lz"
ZacianFrontpic:      INCBIN "gfx/pokemon/zacian/front.animated.2bpp.lz"
ZacianBackpic:      INCBIN "gfx/pokemon/zacian/back.2bpp.lz"
ZebstrikaFrontpic:      INCBIN "gfx/pokemon/zebstrika/front.animated.2bpp.lz"
ZebstrikaBackpic:      INCBIN "gfx/pokemon/zebstrika/back.2bpp.lz"
ZigzagoonFrontpic:      INCBIN "gfx/pokemon/zigzagoon/front.animated.2bpp.lz"
ZigzagoonBackpic:      INCBIN "gfx/pokemon/zigzagoon/back.2bpp.lz"


; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
SenpaiKouhaiPic:        INCBIN "gfx/trainers/senpai_kouhai.2bpp.lz"
SightseerFPic:        INCBIN "gfx/trainers/sightseer_f.2bpp.lz"
SightseerMPic:        INCBIN "gfx/trainers/sightseer_m.2bpp.lz"
SkaterBoyPic:        INCBIN "gfx/trainers/sk8ter_boy.2bpp.lz"
SkierPic:        INCBIN "gfx/trainers/skier.2bpp.lz"
SupervisorPic:        INCBIN "gfx/trainers/supervisor.2bpp.lz"
SwimmerFPic:        INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
SwimmerMPic:        INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
TamerPic:        INCBIN "gfx/trainers/tamer.2bpp.lz"
TeacherPic:        INCBIN "gfx/trainers/teacher.2bpp.lz"
TwinsPic:        INCBIN "gfx/trainers/twins.2bpp.lz"
UndeadPic:        INCBIN "gfx/trainers/undead.2bpp.lz"
WaifuPic:        INCBIN "gfx/trainers/waifu.2bpp.lz"
WeirdoPic:        INCBIN "gfx/trainers/weirdo.2bpp.lz"
WhiteGirlPic:        INCBIN "gfx/trainers/white_girl.2bpp.lz"
WorkerPic:        INCBIN "gfx/trainers/worker.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
BallBrianPic:        INCBIN "gfx/trainers/ball_brian.2bpp.lz"
BrianPic:        INCBIN "gfx/trainers/brian.2bpp.lz"
BrianFPic:        INCBIN "gfx/trainers/brian_f.2bpp.lz"
BrianMPic:        INCBIN "gfx/trainers/brian_m.2bpp.lz"
Brian64Pic:        INCBIN "gfx/trainers/brian64.2bpp.lz"
BugBrianPic:        INCBIN "gfx/trainers/bug_brian.2bpp.lz"
RockBrianPic:        INCBIN "gfx/trainers/rock_brian.2bpp.lz"
TreeBrianPic:        INCBIN "gfx/trainers/tree_brian.2bpp.lz"

SECTION "Pics 21", ROMX

SECTION "Pics 22", ROMX

SECTION "Pics 23", ROMX

SECTION "Pics 24", ROMX
